// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventDeposit(db *gorm.DB, opts ...gen.DOOption) eventDeposit {
	_eventDeposit := eventDeposit{}

	_eventDeposit.eventDepositDo.UseDB(db, opts...)
	_eventDeposit.eventDepositDo.UseModel(&model.EventDeposit{})

	tableName := _eventDeposit.eventDepositDo.TableName()
	_eventDeposit.ALL = field.NewAsterisk(tableName)
	_eventDeposit.ID = field.NewInt64(tableName, "id")
	_eventDeposit.ContractAddress = field.NewString(tableName, "contract_address")
	_eventDeposit.UserAddress = field.NewString(tableName, "user_address")
	_eventDeposit.PoolID = field.NewInt32(tableName, "pool_id")
	_eventDeposit.Amount = field.NewFloat64(tableName, "amount")
	_eventDeposit.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventDeposit.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventDeposit.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventDeposit.LogIndex = field.NewInt32(tableName, "log_index")
	_eventDeposit.CreatedAt = field.NewTime(tableName, "created_at")

	_eventDeposit.fillFieldMap()

	return _eventDeposit
}

// eventDeposit 质押事件表
type eventDeposit struct {
	eventDepositDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	UserAddress     field.String  // 用户地址
	PoolID          field.Int32   // 资金池ID
	Amount          field.Float64 // 质押金额
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventDeposit) Table(newTableName string) *eventDeposit {
	e.eventDepositDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventDeposit) As(alias string) *eventDeposit {
	e.eventDepositDo.DO = *(e.eventDepositDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventDeposit) updateTableName(table string) *eventDeposit {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.UserAddress = field.NewString(table, "user_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.Amount = field.NewFloat64(table, "amount")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventDeposit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventDeposit) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["user_address"] = e.UserAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["amount"] = e.Amount
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventDeposit) clone(db *gorm.DB) eventDeposit {
	e.eventDepositDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventDeposit) replaceDB(db *gorm.DB) eventDeposit {
	e.eventDepositDo.ReplaceDB(db)
	return e
}

type eventDepositDo struct{ gen.DO }

type IEventDepositDo interface {
	gen.SubQuery
	Debug() IEventDepositDo
	WithContext(ctx context.Context) IEventDepositDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventDepositDo
	WriteDB() IEventDepositDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventDepositDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventDepositDo
	Not(conds ...gen.Condition) IEventDepositDo
	Or(conds ...gen.Condition) IEventDepositDo
	Select(conds ...field.Expr) IEventDepositDo
	Where(conds ...gen.Condition) IEventDepositDo
	Order(conds ...field.Expr) IEventDepositDo
	Distinct(cols ...field.Expr) IEventDepositDo
	Omit(cols ...field.Expr) IEventDepositDo
	Join(table schema.Tabler, on ...field.Expr) IEventDepositDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventDepositDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventDepositDo
	Group(cols ...field.Expr) IEventDepositDo
	Having(conds ...gen.Condition) IEventDepositDo
	Limit(limit int) IEventDepositDo
	Offset(offset int) IEventDepositDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventDepositDo
	Unscoped() IEventDepositDo
	Create(values ...*model.EventDeposit) error
	CreateInBatches(values []*model.EventDeposit, batchSize int) error
	Save(values ...*model.EventDeposit) error
	First() (*model.EventDeposit, error)
	Take() (*model.EventDeposit, error)
	Last() (*model.EventDeposit, error)
	Find() ([]*model.EventDeposit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventDeposit, err error)
	FindInBatches(result *[]*model.EventDeposit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventDeposit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventDepositDo
	Assign(attrs ...field.AssignExpr) IEventDepositDo
	Joins(fields ...field.RelationField) IEventDepositDo
	Preload(fields ...field.RelationField) IEventDepositDo
	FirstOrInit() (*model.EventDeposit, error)
	FirstOrCreate() (*model.EventDeposit, error)
	FindByPage(offset int, limit int) (result []*model.EventDeposit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventDepositDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventDepositDo) Debug() IEventDepositDo {
	return e.withDO(e.DO.Debug())
}

func (e eventDepositDo) WithContext(ctx context.Context) IEventDepositDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventDepositDo) ReadDB() IEventDepositDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventDepositDo) WriteDB() IEventDepositDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventDepositDo) Session(config *gorm.Session) IEventDepositDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventDepositDo) Clauses(conds ...clause.Expression) IEventDepositDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventDepositDo) Returning(value interface{}, columns ...string) IEventDepositDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventDepositDo) Not(conds ...gen.Condition) IEventDepositDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventDepositDo) Or(conds ...gen.Condition) IEventDepositDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventDepositDo) Select(conds ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventDepositDo) Where(conds ...gen.Condition) IEventDepositDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventDepositDo) Order(conds ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventDepositDo) Distinct(cols ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventDepositDo) Omit(cols ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventDepositDo) Join(table schema.Tabler, on ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventDepositDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventDepositDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventDepositDo) Group(cols ...field.Expr) IEventDepositDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventDepositDo) Having(conds ...gen.Condition) IEventDepositDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventDepositDo) Limit(limit int) IEventDepositDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventDepositDo) Offset(offset int) IEventDepositDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventDepositDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventDepositDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventDepositDo) Unscoped() IEventDepositDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventDepositDo) Create(values ...*model.EventDeposit) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventDepositDo) CreateInBatches(values []*model.EventDeposit, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventDepositDo) Save(values ...*model.EventDeposit) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventDepositDo) First() (*model.EventDeposit, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDeposit), nil
	}
}

func (e eventDepositDo) Take() (*model.EventDeposit, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDeposit), nil
	}
}

func (e eventDepositDo) Last() (*model.EventDeposit, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDeposit), nil
	}
}

func (e eventDepositDo) Find() ([]*model.EventDeposit, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventDeposit), err
}

func (e eventDepositDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventDeposit, err error) {
	buf := make([]*model.EventDeposit, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventDepositDo) FindInBatches(result *[]*model.EventDeposit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventDepositDo) Attrs(attrs ...field.AssignExpr) IEventDepositDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventDepositDo) Assign(attrs ...field.AssignExpr) IEventDepositDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventDepositDo) Joins(fields ...field.RelationField) IEventDepositDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventDepositDo) Preload(fields ...field.RelationField) IEventDepositDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventDepositDo) FirstOrInit() (*model.EventDeposit, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDeposit), nil
	}
}

func (e eventDepositDo) FirstOrCreate() (*model.EventDeposit, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventDeposit), nil
	}
}

func (e eventDepositDo) FindByPage(offset int, limit int) (result []*model.EventDeposit, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventDepositDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventDepositDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventDepositDo) Delete(models ...*model.EventDeposit) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventDepositDo) withDO(do gen.Dao) *eventDepositDo {
	e.DO = *do.(*gen.DO)
	return e
}
