// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventAddPool(db *gorm.DB, opts ...gen.DOOption) eventAddPool {
	_eventAddPool := eventAddPool{}

	_eventAddPool.eventAddPoolDo.UseDB(db, opts...)
	_eventAddPool.eventAddPoolDo.UseModel(&model.EventAddPool{})

	tableName := _eventAddPool.eventAddPoolDo.TableName()
	_eventAddPool.ALL = field.NewAsterisk(tableName)
	_eventAddPool.ID = field.NewInt64(tableName, "id")
	_eventAddPool.ContractAddress = field.NewString(tableName, "contract_address")
	_eventAddPool.PoolID = field.NewInt32(tableName, "pool_id")
	_eventAddPool.StTokenAddress = field.NewString(tableName, "st_token_address")
	_eventAddPool.PoolWeight = field.NewFloat64(tableName, "pool_weight")
	_eventAddPool.LastRewardBlock = field.NewUint64(tableName, "last_reward_block")
	_eventAddPool.MinDepositAmount = field.NewFloat64(tableName, "min_deposit_amount")
	_eventAddPool.UnstakeLockedBlocks = field.NewInt32(tableName, "unstake_locked_blocks")
	_eventAddPool.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventAddPool.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventAddPool.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventAddPool.LogIndex = field.NewInt32(tableName, "log_index")
	_eventAddPool.CreatedAt = field.NewTime(tableName, "created_at")

	_eventAddPool.fillFieldMap()

	return _eventAddPool
}

// eventAddPool 添加资金池事件表
type eventAddPool struct {
	eventAddPoolDo

	ALL                 field.Asterisk
	ID                  field.Int64
	ContractAddress     field.String
	PoolID              field.Int32   // 资金池ID (根据事件顺序计算)
	StTokenAddress      field.String  // 质押代币地址
	PoolWeight          field.Float64 // 资金池权重
	LastRewardBlock     field.Uint64  // 最后奖励区块
	MinDepositAmount    field.Float64 // 最小质押金额
	UnstakeLockedBlocks field.Int32   // 解锁区块数
	BlockNumber         field.Uint64
	BlockTimestamp      field.Uint64
	TransactionHash     field.String
	LogIndex            field.Int32
	CreatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (e eventAddPool) Table(newTableName string) *eventAddPool {
	e.eventAddPoolDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventAddPool) As(alias string) *eventAddPool {
	e.eventAddPoolDo.DO = *(e.eventAddPoolDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventAddPool) updateTableName(table string) *eventAddPool {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.StTokenAddress = field.NewString(table, "st_token_address")
	e.PoolWeight = field.NewFloat64(table, "pool_weight")
	e.LastRewardBlock = field.NewUint64(table, "last_reward_block")
	e.MinDepositAmount = field.NewFloat64(table, "min_deposit_amount")
	e.UnstakeLockedBlocks = field.NewInt32(table, "unstake_locked_blocks")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventAddPool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventAddPool) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 13)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["st_token_address"] = e.StTokenAddress
	e.fieldMap["pool_weight"] = e.PoolWeight
	e.fieldMap["last_reward_block"] = e.LastRewardBlock
	e.fieldMap["min_deposit_amount"] = e.MinDepositAmount
	e.fieldMap["unstake_locked_blocks"] = e.UnstakeLockedBlocks
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventAddPool) clone(db *gorm.DB) eventAddPool {
	e.eventAddPoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventAddPool) replaceDB(db *gorm.DB) eventAddPool {
	e.eventAddPoolDo.ReplaceDB(db)
	return e
}

type eventAddPoolDo struct{ gen.DO }

type IEventAddPoolDo interface {
	gen.SubQuery
	Debug() IEventAddPoolDo
	WithContext(ctx context.Context) IEventAddPoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventAddPoolDo
	WriteDB() IEventAddPoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventAddPoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventAddPoolDo
	Not(conds ...gen.Condition) IEventAddPoolDo
	Or(conds ...gen.Condition) IEventAddPoolDo
	Select(conds ...field.Expr) IEventAddPoolDo
	Where(conds ...gen.Condition) IEventAddPoolDo
	Order(conds ...field.Expr) IEventAddPoolDo
	Distinct(cols ...field.Expr) IEventAddPoolDo
	Omit(cols ...field.Expr) IEventAddPoolDo
	Join(table schema.Tabler, on ...field.Expr) IEventAddPoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventAddPoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventAddPoolDo
	Group(cols ...field.Expr) IEventAddPoolDo
	Having(conds ...gen.Condition) IEventAddPoolDo
	Limit(limit int) IEventAddPoolDo
	Offset(offset int) IEventAddPoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventAddPoolDo
	Unscoped() IEventAddPoolDo
	Create(values ...*model.EventAddPool) error
	CreateInBatches(values []*model.EventAddPool, batchSize int) error
	Save(values ...*model.EventAddPool) error
	First() (*model.EventAddPool, error)
	Take() (*model.EventAddPool, error)
	Last() (*model.EventAddPool, error)
	Find() ([]*model.EventAddPool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventAddPool, err error)
	FindInBatches(result *[]*model.EventAddPool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventAddPool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventAddPoolDo
	Assign(attrs ...field.AssignExpr) IEventAddPoolDo
	Joins(fields ...field.RelationField) IEventAddPoolDo
	Preload(fields ...field.RelationField) IEventAddPoolDo
	FirstOrInit() (*model.EventAddPool, error)
	FirstOrCreate() (*model.EventAddPool, error)
	FindByPage(offset int, limit int) (result []*model.EventAddPool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventAddPoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventAddPoolDo) Debug() IEventAddPoolDo {
	return e.withDO(e.DO.Debug())
}

func (e eventAddPoolDo) WithContext(ctx context.Context) IEventAddPoolDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventAddPoolDo) ReadDB() IEventAddPoolDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventAddPoolDo) WriteDB() IEventAddPoolDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventAddPoolDo) Session(config *gorm.Session) IEventAddPoolDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventAddPoolDo) Clauses(conds ...clause.Expression) IEventAddPoolDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventAddPoolDo) Returning(value interface{}, columns ...string) IEventAddPoolDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventAddPoolDo) Not(conds ...gen.Condition) IEventAddPoolDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventAddPoolDo) Or(conds ...gen.Condition) IEventAddPoolDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventAddPoolDo) Select(conds ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventAddPoolDo) Where(conds ...gen.Condition) IEventAddPoolDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventAddPoolDo) Order(conds ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventAddPoolDo) Distinct(cols ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventAddPoolDo) Omit(cols ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventAddPoolDo) Join(table schema.Tabler, on ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventAddPoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventAddPoolDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventAddPoolDo) Group(cols ...field.Expr) IEventAddPoolDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventAddPoolDo) Having(conds ...gen.Condition) IEventAddPoolDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventAddPoolDo) Limit(limit int) IEventAddPoolDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventAddPoolDo) Offset(offset int) IEventAddPoolDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventAddPoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventAddPoolDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventAddPoolDo) Unscoped() IEventAddPoolDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventAddPoolDo) Create(values ...*model.EventAddPool) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventAddPoolDo) CreateInBatches(values []*model.EventAddPool, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventAddPoolDo) Save(values ...*model.EventAddPool) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventAddPoolDo) First() (*model.EventAddPool, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventAddPool), nil
	}
}

func (e eventAddPoolDo) Take() (*model.EventAddPool, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventAddPool), nil
	}
}

func (e eventAddPoolDo) Last() (*model.EventAddPool, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventAddPool), nil
	}
}

func (e eventAddPoolDo) Find() ([]*model.EventAddPool, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventAddPool), err
}

func (e eventAddPoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventAddPool, err error) {
	buf := make([]*model.EventAddPool, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventAddPoolDo) FindInBatches(result *[]*model.EventAddPool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventAddPoolDo) Attrs(attrs ...field.AssignExpr) IEventAddPoolDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventAddPoolDo) Assign(attrs ...field.AssignExpr) IEventAddPoolDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventAddPoolDo) Joins(fields ...field.RelationField) IEventAddPoolDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventAddPoolDo) Preload(fields ...field.RelationField) IEventAddPoolDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventAddPoolDo) FirstOrInit() (*model.EventAddPool, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventAddPool), nil
	}
}

func (e eventAddPoolDo) FirstOrCreate() (*model.EventAddPool, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventAddPool), nil
	}
}

func (e eventAddPoolDo) FindByPage(offset int, limit int) (result []*model.EventAddPool, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventAddPoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventAddPoolDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventAddPoolDo) Delete(models ...*model.EventAddPool) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventAddPoolDo) withDO(do gen.Dao) *eventAddPoolDo {
	e.DO = *do.(*gen.DO)
	return e
}
