// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventPauseWithdraw(db *gorm.DB, opts ...gen.DOOption) eventPauseWithdraw {
	_eventPauseWithdraw := eventPauseWithdraw{}

	_eventPauseWithdraw.eventPauseWithdrawDo.UseDB(db, opts...)
	_eventPauseWithdraw.eventPauseWithdrawDo.UseModel(&model.EventPauseWithdraw{})

	tableName := _eventPauseWithdraw.eventPauseWithdrawDo.TableName()
	_eventPauseWithdraw.ALL = field.NewAsterisk(tableName)
	_eventPauseWithdraw.ID = field.NewInt64(tableName, "id")
	_eventPauseWithdraw.ContractAddress = field.NewString(tableName, "contract_address")
	_eventPauseWithdraw.IsPaused = field.NewBool(tableName, "is_paused")
	_eventPauseWithdraw.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventPauseWithdraw.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventPauseWithdraw.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventPauseWithdraw.LogIndex = field.NewInt32(tableName, "log_index")
	_eventPauseWithdraw.CreatedAt = field.NewTime(tableName, "created_at")

	_eventPauseWithdraw.fillFieldMap()

	return _eventPauseWithdraw
}

// eventPauseWithdraw 暂停/恢复提现事件表
type eventPauseWithdraw struct {
	eventPauseWithdrawDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	IsPaused        field.Bool // 是否暂停 (true=暂停, false=恢复)
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventPauseWithdraw) Table(newTableName string) *eventPauseWithdraw {
	e.eventPauseWithdrawDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventPauseWithdraw) As(alias string) *eventPauseWithdraw {
	e.eventPauseWithdrawDo.DO = *(e.eventPauseWithdrawDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventPauseWithdraw) updateTableName(table string) *eventPauseWithdraw {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.IsPaused = field.NewBool(table, "is_paused")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventPauseWithdraw) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventPauseWithdraw) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["is_paused"] = e.IsPaused
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventPauseWithdraw) clone(db *gorm.DB) eventPauseWithdraw {
	e.eventPauseWithdrawDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventPauseWithdraw) replaceDB(db *gorm.DB) eventPauseWithdraw {
	e.eventPauseWithdrawDo.ReplaceDB(db)
	return e
}

type eventPauseWithdrawDo struct{ gen.DO }

type IEventPauseWithdrawDo interface {
	gen.SubQuery
	Debug() IEventPauseWithdrawDo
	WithContext(ctx context.Context) IEventPauseWithdrawDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventPauseWithdrawDo
	WriteDB() IEventPauseWithdrawDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventPauseWithdrawDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventPauseWithdrawDo
	Not(conds ...gen.Condition) IEventPauseWithdrawDo
	Or(conds ...gen.Condition) IEventPauseWithdrawDo
	Select(conds ...field.Expr) IEventPauseWithdrawDo
	Where(conds ...gen.Condition) IEventPauseWithdrawDo
	Order(conds ...field.Expr) IEventPauseWithdrawDo
	Distinct(cols ...field.Expr) IEventPauseWithdrawDo
	Omit(cols ...field.Expr) IEventPauseWithdrawDo
	Join(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo
	Group(cols ...field.Expr) IEventPauseWithdrawDo
	Having(conds ...gen.Condition) IEventPauseWithdrawDo
	Limit(limit int) IEventPauseWithdrawDo
	Offset(offset int) IEventPauseWithdrawDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventPauseWithdrawDo
	Unscoped() IEventPauseWithdrawDo
	Create(values ...*model.EventPauseWithdraw) error
	CreateInBatches(values []*model.EventPauseWithdraw, batchSize int) error
	Save(values ...*model.EventPauseWithdraw) error
	First() (*model.EventPauseWithdraw, error)
	Take() (*model.EventPauseWithdraw, error)
	Last() (*model.EventPauseWithdraw, error)
	Find() ([]*model.EventPauseWithdraw, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventPauseWithdraw, err error)
	FindInBatches(result *[]*model.EventPauseWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventPauseWithdraw) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventPauseWithdrawDo
	Assign(attrs ...field.AssignExpr) IEventPauseWithdrawDo
	Joins(fields ...field.RelationField) IEventPauseWithdrawDo
	Preload(fields ...field.RelationField) IEventPauseWithdrawDo
	FirstOrInit() (*model.EventPauseWithdraw, error)
	FirstOrCreate() (*model.EventPauseWithdraw, error)
	FindByPage(offset int, limit int) (result []*model.EventPauseWithdraw, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventPauseWithdrawDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventPauseWithdrawDo) Debug() IEventPauseWithdrawDo {
	return e.withDO(e.DO.Debug())
}

func (e eventPauseWithdrawDo) WithContext(ctx context.Context) IEventPauseWithdrawDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventPauseWithdrawDo) ReadDB() IEventPauseWithdrawDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventPauseWithdrawDo) WriteDB() IEventPauseWithdrawDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventPauseWithdrawDo) Session(config *gorm.Session) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventPauseWithdrawDo) Clauses(conds ...clause.Expression) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventPauseWithdrawDo) Returning(value interface{}, columns ...string) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventPauseWithdrawDo) Not(conds ...gen.Condition) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventPauseWithdrawDo) Or(conds ...gen.Condition) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventPauseWithdrawDo) Select(conds ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventPauseWithdrawDo) Where(conds ...gen.Condition) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventPauseWithdrawDo) Order(conds ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventPauseWithdrawDo) Distinct(cols ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventPauseWithdrawDo) Omit(cols ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventPauseWithdrawDo) Join(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventPauseWithdrawDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventPauseWithdrawDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventPauseWithdrawDo) Group(cols ...field.Expr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventPauseWithdrawDo) Having(conds ...gen.Condition) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventPauseWithdrawDo) Limit(limit int) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventPauseWithdrawDo) Offset(offset int) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventPauseWithdrawDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventPauseWithdrawDo) Unscoped() IEventPauseWithdrawDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventPauseWithdrawDo) Create(values ...*model.EventPauseWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventPauseWithdrawDo) CreateInBatches(values []*model.EventPauseWithdraw, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventPauseWithdrawDo) Save(values ...*model.EventPauseWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventPauseWithdrawDo) First() (*model.EventPauseWithdraw, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseWithdraw), nil
	}
}

func (e eventPauseWithdrawDo) Take() (*model.EventPauseWithdraw, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseWithdraw), nil
	}
}

func (e eventPauseWithdrawDo) Last() (*model.EventPauseWithdraw, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseWithdraw), nil
	}
}

func (e eventPauseWithdrawDo) Find() ([]*model.EventPauseWithdraw, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventPauseWithdraw), err
}

func (e eventPauseWithdrawDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventPauseWithdraw, err error) {
	buf := make([]*model.EventPauseWithdraw, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventPauseWithdrawDo) FindInBatches(result *[]*model.EventPauseWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventPauseWithdrawDo) Attrs(attrs ...field.AssignExpr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventPauseWithdrawDo) Assign(attrs ...field.AssignExpr) IEventPauseWithdrawDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventPauseWithdrawDo) Joins(fields ...field.RelationField) IEventPauseWithdrawDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventPauseWithdrawDo) Preload(fields ...field.RelationField) IEventPauseWithdrawDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventPauseWithdrawDo) FirstOrInit() (*model.EventPauseWithdraw, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseWithdraw), nil
	}
}

func (e eventPauseWithdrawDo) FirstOrCreate() (*model.EventPauseWithdraw, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseWithdraw), nil
	}
}

func (e eventPauseWithdrawDo) FindByPage(offset int, limit int) (result []*model.EventPauseWithdraw, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventPauseWithdrawDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventPauseWithdrawDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventPauseWithdrawDo) Delete(models ...*model.EventPauseWithdraw) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventPauseWithdrawDo) withDO(do gen.Dao) *eventPauseWithdrawDo {
	e.DO = *do.(*gen.DO)
	return e
}
