// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventClaim(db *gorm.DB, opts ...gen.DOOption) eventClaim {
	_eventClaim := eventClaim{}

	_eventClaim.eventClaimDo.UseDB(db, opts...)
	_eventClaim.eventClaimDo.UseModel(&model.EventClaim{})

	tableName := _eventClaim.eventClaimDo.TableName()
	_eventClaim.ALL = field.NewAsterisk(tableName)
	_eventClaim.ID = field.NewInt64(tableName, "id")
	_eventClaim.ContractAddress = field.NewString(tableName, "contract_address")
	_eventClaim.UserAddress = field.NewString(tableName, "user_address")
	_eventClaim.PoolID = field.NewInt32(tableName, "pool_id")
	_eventClaim.MetanodeReward = field.NewFloat64(tableName, "metanode_reward")
	_eventClaim.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventClaim.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventClaim.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventClaim.LogIndex = field.NewInt32(tableName, "log_index")
	_eventClaim.CreatedAt = field.NewTime(tableName, "created_at")

	_eventClaim.fillFieldMap()

	return _eventClaim
}

// eventClaim 领取奖励事件表
type eventClaim struct {
	eventClaimDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	UserAddress     field.String  // 用户地址
	PoolID          field.Int32   // 资金池ID
	MetanodeReward  field.Float64 // 领取的MetaNode奖励
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventClaim) Table(newTableName string) *eventClaim {
	e.eventClaimDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventClaim) As(alias string) *eventClaim {
	e.eventClaimDo.DO = *(e.eventClaimDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventClaim) updateTableName(table string) *eventClaim {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.UserAddress = field.NewString(table, "user_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.MetanodeReward = field.NewFloat64(table, "metanode_reward")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventClaim) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventClaim) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["user_address"] = e.UserAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["metanode_reward"] = e.MetanodeReward
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventClaim) clone(db *gorm.DB) eventClaim {
	e.eventClaimDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventClaim) replaceDB(db *gorm.DB) eventClaim {
	e.eventClaimDo.ReplaceDB(db)
	return e
}

type eventClaimDo struct{ gen.DO }

type IEventClaimDo interface {
	gen.SubQuery
	Debug() IEventClaimDo
	WithContext(ctx context.Context) IEventClaimDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventClaimDo
	WriteDB() IEventClaimDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventClaimDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventClaimDo
	Not(conds ...gen.Condition) IEventClaimDo
	Or(conds ...gen.Condition) IEventClaimDo
	Select(conds ...field.Expr) IEventClaimDo
	Where(conds ...gen.Condition) IEventClaimDo
	Order(conds ...field.Expr) IEventClaimDo
	Distinct(cols ...field.Expr) IEventClaimDo
	Omit(cols ...field.Expr) IEventClaimDo
	Join(table schema.Tabler, on ...field.Expr) IEventClaimDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventClaimDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventClaimDo
	Group(cols ...field.Expr) IEventClaimDo
	Having(conds ...gen.Condition) IEventClaimDo
	Limit(limit int) IEventClaimDo
	Offset(offset int) IEventClaimDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventClaimDo
	Unscoped() IEventClaimDo
	Create(values ...*model.EventClaim) error
	CreateInBatches(values []*model.EventClaim, batchSize int) error
	Save(values ...*model.EventClaim) error
	First() (*model.EventClaim, error)
	Take() (*model.EventClaim, error)
	Last() (*model.EventClaim, error)
	Find() ([]*model.EventClaim, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventClaim, err error)
	FindInBatches(result *[]*model.EventClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventClaim) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventClaimDo
	Assign(attrs ...field.AssignExpr) IEventClaimDo
	Joins(fields ...field.RelationField) IEventClaimDo
	Preload(fields ...field.RelationField) IEventClaimDo
	FirstOrInit() (*model.EventClaim, error)
	FirstOrCreate() (*model.EventClaim, error)
	FindByPage(offset int, limit int) (result []*model.EventClaim, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventClaimDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventClaimDo) Debug() IEventClaimDo {
	return e.withDO(e.DO.Debug())
}

func (e eventClaimDo) WithContext(ctx context.Context) IEventClaimDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventClaimDo) ReadDB() IEventClaimDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventClaimDo) WriteDB() IEventClaimDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventClaimDo) Session(config *gorm.Session) IEventClaimDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventClaimDo) Clauses(conds ...clause.Expression) IEventClaimDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventClaimDo) Returning(value interface{}, columns ...string) IEventClaimDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventClaimDo) Not(conds ...gen.Condition) IEventClaimDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventClaimDo) Or(conds ...gen.Condition) IEventClaimDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventClaimDo) Select(conds ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventClaimDo) Where(conds ...gen.Condition) IEventClaimDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventClaimDo) Order(conds ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventClaimDo) Distinct(cols ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventClaimDo) Omit(cols ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventClaimDo) Join(table schema.Tabler, on ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventClaimDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventClaimDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventClaimDo) Group(cols ...field.Expr) IEventClaimDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventClaimDo) Having(conds ...gen.Condition) IEventClaimDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventClaimDo) Limit(limit int) IEventClaimDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventClaimDo) Offset(offset int) IEventClaimDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventClaimDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventClaimDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventClaimDo) Unscoped() IEventClaimDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventClaimDo) Create(values ...*model.EventClaim) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventClaimDo) CreateInBatches(values []*model.EventClaim, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventClaimDo) Save(values ...*model.EventClaim) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventClaimDo) First() (*model.EventClaim, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventClaim), nil
	}
}

func (e eventClaimDo) Take() (*model.EventClaim, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventClaim), nil
	}
}

func (e eventClaimDo) Last() (*model.EventClaim, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventClaim), nil
	}
}

func (e eventClaimDo) Find() ([]*model.EventClaim, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventClaim), err
}

func (e eventClaimDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventClaim, err error) {
	buf := make([]*model.EventClaim, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventClaimDo) FindInBatches(result *[]*model.EventClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventClaimDo) Attrs(attrs ...field.AssignExpr) IEventClaimDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventClaimDo) Assign(attrs ...field.AssignExpr) IEventClaimDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventClaimDo) Joins(fields ...field.RelationField) IEventClaimDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventClaimDo) Preload(fields ...field.RelationField) IEventClaimDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventClaimDo) FirstOrInit() (*model.EventClaim, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventClaim), nil
	}
}

func (e eventClaimDo) FirstOrCreate() (*model.EventClaim, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventClaim), nil
	}
}

func (e eventClaimDo) FindByPage(offset int, limit int) (result []*model.EventClaim, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventClaimDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventClaimDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventClaimDo) Delete(models ...*model.EventClaim) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventClaimDo) withDO(do gen.Dao) *eventClaimDo {
	e.DO = *do.(*gen.DO)
	return e
}
