// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventPauseClaim(db *gorm.DB, opts ...gen.DOOption) eventPauseClaim {
	_eventPauseClaim := eventPauseClaim{}

	_eventPauseClaim.eventPauseClaimDo.UseDB(db, opts...)
	_eventPauseClaim.eventPauseClaimDo.UseModel(&model.EventPauseClaim{})

	tableName := _eventPauseClaim.eventPauseClaimDo.TableName()
	_eventPauseClaim.ALL = field.NewAsterisk(tableName)
	_eventPauseClaim.ID = field.NewInt64(tableName, "id")
	_eventPauseClaim.ContractAddress = field.NewString(tableName, "contract_address")
	_eventPauseClaim.IsPaused = field.NewBool(tableName, "is_paused")
	_eventPauseClaim.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventPauseClaim.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventPauseClaim.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventPauseClaim.LogIndex = field.NewInt32(tableName, "log_index")
	_eventPauseClaim.CreatedAt = field.NewTime(tableName, "created_at")

	_eventPauseClaim.fillFieldMap()

	return _eventPauseClaim
}

// eventPauseClaim 暂停/恢复领取事件表
type eventPauseClaim struct {
	eventPauseClaimDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	IsPaused        field.Bool // 是否暂停 (true=暂停, false=恢复)
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventPauseClaim) Table(newTableName string) *eventPauseClaim {
	e.eventPauseClaimDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventPauseClaim) As(alias string) *eventPauseClaim {
	e.eventPauseClaimDo.DO = *(e.eventPauseClaimDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventPauseClaim) updateTableName(table string) *eventPauseClaim {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.IsPaused = field.NewBool(table, "is_paused")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventPauseClaim) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventPauseClaim) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["is_paused"] = e.IsPaused
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventPauseClaim) clone(db *gorm.DB) eventPauseClaim {
	e.eventPauseClaimDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventPauseClaim) replaceDB(db *gorm.DB) eventPauseClaim {
	e.eventPauseClaimDo.ReplaceDB(db)
	return e
}

type eventPauseClaimDo struct{ gen.DO }

type IEventPauseClaimDo interface {
	gen.SubQuery
	Debug() IEventPauseClaimDo
	WithContext(ctx context.Context) IEventPauseClaimDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventPauseClaimDo
	WriteDB() IEventPauseClaimDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventPauseClaimDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventPauseClaimDo
	Not(conds ...gen.Condition) IEventPauseClaimDo
	Or(conds ...gen.Condition) IEventPauseClaimDo
	Select(conds ...field.Expr) IEventPauseClaimDo
	Where(conds ...gen.Condition) IEventPauseClaimDo
	Order(conds ...field.Expr) IEventPauseClaimDo
	Distinct(cols ...field.Expr) IEventPauseClaimDo
	Omit(cols ...field.Expr) IEventPauseClaimDo
	Join(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo
	Group(cols ...field.Expr) IEventPauseClaimDo
	Having(conds ...gen.Condition) IEventPauseClaimDo
	Limit(limit int) IEventPauseClaimDo
	Offset(offset int) IEventPauseClaimDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventPauseClaimDo
	Unscoped() IEventPauseClaimDo
	Create(values ...*model.EventPauseClaim) error
	CreateInBatches(values []*model.EventPauseClaim, batchSize int) error
	Save(values ...*model.EventPauseClaim) error
	First() (*model.EventPauseClaim, error)
	Take() (*model.EventPauseClaim, error)
	Last() (*model.EventPauseClaim, error)
	Find() ([]*model.EventPauseClaim, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventPauseClaim, err error)
	FindInBatches(result *[]*model.EventPauseClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventPauseClaim) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventPauseClaimDo
	Assign(attrs ...field.AssignExpr) IEventPauseClaimDo
	Joins(fields ...field.RelationField) IEventPauseClaimDo
	Preload(fields ...field.RelationField) IEventPauseClaimDo
	FirstOrInit() (*model.EventPauseClaim, error)
	FirstOrCreate() (*model.EventPauseClaim, error)
	FindByPage(offset int, limit int) (result []*model.EventPauseClaim, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventPauseClaimDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventPauseClaimDo) Debug() IEventPauseClaimDo {
	return e.withDO(e.DO.Debug())
}

func (e eventPauseClaimDo) WithContext(ctx context.Context) IEventPauseClaimDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventPauseClaimDo) ReadDB() IEventPauseClaimDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventPauseClaimDo) WriteDB() IEventPauseClaimDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventPauseClaimDo) Session(config *gorm.Session) IEventPauseClaimDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventPauseClaimDo) Clauses(conds ...clause.Expression) IEventPauseClaimDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventPauseClaimDo) Returning(value interface{}, columns ...string) IEventPauseClaimDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventPauseClaimDo) Not(conds ...gen.Condition) IEventPauseClaimDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventPauseClaimDo) Or(conds ...gen.Condition) IEventPauseClaimDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventPauseClaimDo) Select(conds ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventPauseClaimDo) Where(conds ...gen.Condition) IEventPauseClaimDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventPauseClaimDo) Order(conds ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventPauseClaimDo) Distinct(cols ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventPauseClaimDo) Omit(cols ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventPauseClaimDo) Join(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventPauseClaimDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventPauseClaimDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventPauseClaimDo) Group(cols ...field.Expr) IEventPauseClaimDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventPauseClaimDo) Having(conds ...gen.Condition) IEventPauseClaimDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventPauseClaimDo) Limit(limit int) IEventPauseClaimDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventPauseClaimDo) Offset(offset int) IEventPauseClaimDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventPauseClaimDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventPauseClaimDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventPauseClaimDo) Unscoped() IEventPauseClaimDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventPauseClaimDo) Create(values ...*model.EventPauseClaim) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventPauseClaimDo) CreateInBatches(values []*model.EventPauseClaim, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventPauseClaimDo) Save(values ...*model.EventPauseClaim) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventPauseClaimDo) First() (*model.EventPauseClaim, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseClaim), nil
	}
}

func (e eventPauseClaimDo) Take() (*model.EventPauseClaim, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseClaim), nil
	}
}

func (e eventPauseClaimDo) Last() (*model.EventPauseClaim, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseClaim), nil
	}
}

func (e eventPauseClaimDo) Find() ([]*model.EventPauseClaim, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventPauseClaim), err
}

func (e eventPauseClaimDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventPauseClaim, err error) {
	buf := make([]*model.EventPauseClaim, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventPauseClaimDo) FindInBatches(result *[]*model.EventPauseClaim, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventPauseClaimDo) Attrs(attrs ...field.AssignExpr) IEventPauseClaimDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventPauseClaimDo) Assign(attrs ...field.AssignExpr) IEventPauseClaimDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventPauseClaimDo) Joins(fields ...field.RelationField) IEventPauseClaimDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventPauseClaimDo) Preload(fields ...field.RelationField) IEventPauseClaimDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventPauseClaimDo) FirstOrInit() (*model.EventPauseClaim, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseClaim), nil
	}
}

func (e eventPauseClaimDo) FirstOrCreate() (*model.EventPauseClaim, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventPauseClaim), nil
	}
}

func (e eventPauseClaimDo) FindByPage(offset int, limit int) (result []*model.EventPauseClaim, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventPauseClaimDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventPauseClaimDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventPauseClaimDo) Delete(models ...*model.EventPauseClaim) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventPauseClaimDo) withDO(do gen.Dao) *eventPauseClaimDo {
	e.DO = *do.(*gen.DO)
	return e
}
