// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventWithdraw(db *gorm.DB, opts ...gen.DOOption) eventWithdraw {
	_eventWithdraw := eventWithdraw{}

	_eventWithdraw.eventWithdrawDo.UseDB(db, opts...)
	_eventWithdraw.eventWithdrawDo.UseModel(&model.EventWithdraw{})

	tableName := _eventWithdraw.eventWithdrawDo.TableName()
	_eventWithdraw.ALL = field.NewAsterisk(tableName)
	_eventWithdraw.ID = field.NewInt64(tableName, "id")
	_eventWithdraw.ContractAddress = field.NewString(tableName, "contract_address")
	_eventWithdraw.UserAddress = field.NewString(tableName, "user_address")
	_eventWithdraw.PoolID = field.NewInt32(tableName, "pool_id")
	_eventWithdraw.Amount = field.NewFloat64(tableName, "amount")
	_eventWithdraw.WithdrawBlockNumber = field.NewUint64(tableName, "withdraw_block_number")
	_eventWithdraw.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventWithdraw.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventWithdraw.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventWithdraw.LogIndex = field.NewInt32(tableName, "log_index")
	_eventWithdraw.CreatedAt = field.NewTime(tableName, "created_at")

	_eventWithdraw.fillFieldMap()

	return _eventWithdraw
}

// eventWithdraw 提现事件表
type eventWithdraw struct {
	eventWithdrawDo

	ALL                 field.Asterisk
	ID                  field.Int64
	ContractAddress     field.String
	UserAddress         field.String  // 用户地址
	PoolID              field.Int32   // 资金池ID
	Amount              field.Float64 // 提现金额
	WithdrawBlockNumber field.Uint64  // 提现时的区块号
	BlockNumber         field.Uint64
	BlockTimestamp      field.Uint64
	TransactionHash     field.String
	LogIndex            field.Int32
	CreatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (e eventWithdraw) Table(newTableName string) *eventWithdraw {
	e.eventWithdrawDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventWithdraw) As(alias string) *eventWithdraw {
	e.eventWithdrawDo.DO = *(e.eventWithdrawDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventWithdraw) updateTableName(table string) *eventWithdraw {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.UserAddress = field.NewString(table, "user_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.Amount = field.NewFloat64(table, "amount")
	e.WithdrawBlockNumber = field.NewUint64(table, "withdraw_block_number")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventWithdraw) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventWithdraw) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 11)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["user_address"] = e.UserAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["amount"] = e.Amount
	e.fieldMap["withdraw_block_number"] = e.WithdrawBlockNumber
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventWithdraw) clone(db *gorm.DB) eventWithdraw {
	e.eventWithdrawDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventWithdraw) replaceDB(db *gorm.DB) eventWithdraw {
	e.eventWithdrawDo.ReplaceDB(db)
	return e
}

type eventWithdrawDo struct{ gen.DO }

type IEventWithdrawDo interface {
	gen.SubQuery
	Debug() IEventWithdrawDo
	WithContext(ctx context.Context) IEventWithdrawDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventWithdrawDo
	WriteDB() IEventWithdrawDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventWithdrawDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventWithdrawDo
	Not(conds ...gen.Condition) IEventWithdrawDo
	Or(conds ...gen.Condition) IEventWithdrawDo
	Select(conds ...field.Expr) IEventWithdrawDo
	Where(conds ...gen.Condition) IEventWithdrawDo
	Order(conds ...field.Expr) IEventWithdrawDo
	Distinct(cols ...field.Expr) IEventWithdrawDo
	Omit(cols ...field.Expr) IEventWithdrawDo
	Join(table schema.Tabler, on ...field.Expr) IEventWithdrawDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventWithdrawDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventWithdrawDo
	Group(cols ...field.Expr) IEventWithdrawDo
	Having(conds ...gen.Condition) IEventWithdrawDo
	Limit(limit int) IEventWithdrawDo
	Offset(offset int) IEventWithdrawDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventWithdrawDo
	Unscoped() IEventWithdrawDo
	Create(values ...*model.EventWithdraw) error
	CreateInBatches(values []*model.EventWithdraw, batchSize int) error
	Save(values ...*model.EventWithdraw) error
	First() (*model.EventWithdraw, error)
	Take() (*model.EventWithdraw, error)
	Last() (*model.EventWithdraw, error)
	Find() ([]*model.EventWithdraw, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventWithdraw, err error)
	FindInBatches(result *[]*model.EventWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventWithdraw) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventWithdrawDo
	Assign(attrs ...field.AssignExpr) IEventWithdrawDo
	Joins(fields ...field.RelationField) IEventWithdrawDo
	Preload(fields ...field.RelationField) IEventWithdrawDo
	FirstOrInit() (*model.EventWithdraw, error)
	FirstOrCreate() (*model.EventWithdraw, error)
	FindByPage(offset int, limit int) (result []*model.EventWithdraw, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventWithdrawDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventWithdrawDo) Debug() IEventWithdrawDo {
	return e.withDO(e.DO.Debug())
}

func (e eventWithdrawDo) WithContext(ctx context.Context) IEventWithdrawDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventWithdrawDo) ReadDB() IEventWithdrawDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventWithdrawDo) WriteDB() IEventWithdrawDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventWithdrawDo) Session(config *gorm.Session) IEventWithdrawDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventWithdrawDo) Clauses(conds ...clause.Expression) IEventWithdrawDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventWithdrawDo) Returning(value interface{}, columns ...string) IEventWithdrawDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventWithdrawDo) Not(conds ...gen.Condition) IEventWithdrawDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventWithdrawDo) Or(conds ...gen.Condition) IEventWithdrawDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventWithdrawDo) Select(conds ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventWithdrawDo) Where(conds ...gen.Condition) IEventWithdrawDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventWithdrawDo) Order(conds ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventWithdrawDo) Distinct(cols ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventWithdrawDo) Omit(cols ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventWithdrawDo) Join(table schema.Tabler, on ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventWithdrawDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventWithdrawDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventWithdrawDo) Group(cols ...field.Expr) IEventWithdrawDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventWithdrawDo) Having(conds ...gen.Condition) IEventWithdrawDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventWithdrawDo) Limit(limit int) IEventWithdrawDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventWithdrawDo) Offset(offset int) IEventWithdrawDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventWithdrawDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventWithdrawDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventWithdrawDo) Unscoped() IEventWithdrawDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventWithdrawDo) Create(values ...*model.EventWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventWithdrawDo) CreateInBatches(values []*model.EventWithdraw, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventWithdrawDo) Save(values ...*model.EventWithdraw) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventWithdrawDo) First() (*model.EventWithdraw, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventWithdraw), nil
	}
}

func (e eventWithdrawDo) Take() (*model.EventWithdraw, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventWithdraw), nil
	}
}

func (e eventWithdrawDo) Last() (*model.EventWithdraw, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventWithdraw), nil
	}
}

func (e eventWithdrawDo) Find() ([]*model.EventWithdraw, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventWithdraw), err
}

func (e eventWithdrawDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventWithdraw, err error) {
	buf := make([]*model.EventWithdraw, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventWithdrawDo) FindInBatches(result *[]*model.EventWithdraw, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventWithdrawDo) Attrs(attrs ...field.AssignExpr) IEventWithdrawDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventWithdrawDo) Assign(attrs ...field.AssignExpr) IEventWithdrawDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventWithdrawDo) Joins(fields ...field.RelationField) IEventWithdrawDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventWithdrawDo) Preload(fields ...field.RelationField) IEventWithdrawDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventWithdrawDo) FirstOrInit() (*model.EventWithdraw, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventWithdraw), nil
	}
}

func (e eventWithdrawDo) FirstOrCreate() (*model.EventWithdraw, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventWithdraw), nil
	}
}

func (e eventWithdrawDo) FindByPage(offset int, limit int) (result []*model.EventWithdraw, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventWithdrawDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventWithdrawDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventWithdrawDo) Delete(models ...*model.EventWithdraw) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventWithdrawDo) withDO(do gen.Dao) *eventWithdrawDo {
	e.DO = *do.(*gen.DO)
	return e
}
