// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventSetStartBlock(db *gorm.DB, opts ...gen.DOOption) eventSetStartBlock {
	_eventSetStartBlock := eventSetStartBlock{}

	_eventSetStartBlock.eventSetStartBlockDo.UseDB(db, opts...)
	_eventSetStartBlock.eventSetStartBlockDo.UseModel(&model.EventSetStartBlock{})

	tableName := _eventSetStartBlock.eventSetStartBlockDo.TableName()
	_eventSetStartBlock.ALL = field.NewAsterisk(tableName)
	_eventSetStartBlock.ID = field.NewInt64(tableName, "id")
	_eventSetStartBlock.ContractAddress = field.NewString(tableName, "contract_address")
	_eventSetStartBlock.StartBlock = field.NewUint64(tableName, "start_block")
	_eventSetStartBlock.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventSetStartBlock.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventSetStartBlock.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventSetStartBlock.LogIndex = field.NewInt32(tableName, "log_index")
	_eventSetStartBlock.CreatedAt = field.NewTime(tableName, "created_at")

	_eventSetStartBlock.fillFieldMap()

	return _eventSetStartBlock
}

// eventSetStartBlock 设置开始区块事件表
type eventSetStartBlock struct {
	eventSetStartBlockDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	StartBlock      field.Uint64 // 质押开始区块
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventSetStartBlock) Table(newTableName string) *eventSetStartBlock {
	e.eventSetStartBlockDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventSetStartBlock) As(alias string) *eventSetStartBlock {
	e.eventSetStartBlockDo.DO = *(e.eventSetStartBlockDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventSetStartBlock) updateTableName(table string) *eventSetStartBlock {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.StartBlock = field.NewUint64(table, "start_block")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventSetStartBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventSetStartBlock) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["start_block"] = e.StartBlock
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventSetStartBlock) clone(db *gorm.DB) eventSetStartBlock {
	e.eventSetStartBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventSetStartBlock) replaceDB(db *gorm.DB) eventSetStartBlock {
	e.eventSetStartBlockDo.ReplaceDB(db)
	return e
}

type eventSetStartBlockDo struct{ gen.DO }

type IEventSetStartBlockDo interface {
	gen.SubQuery
	Debug() IEventSetStartBlockDo
	WithContext(ctx context.Context) IEventSetStartBlockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventSetStartBlockDo
	WriteDB() IEventSetStartBlockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventSetStartBlockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventSetStartBlockDo
	Not(conds ...gen.Condition) IEventSetStartBlockDo
	Or(conds ...gen.Condition) IEventSetStartBlockDo
	Select(conds ...field.Expr) IEventSetStartBlockDo
	Where(conds ...gen.Condition) IEventSetStartBlockDo
	Order(conds ...field.Expr) IEventSetStartBlockDo
	Distinct(cols ...field.Expr) IEventSetStartBlockDo
	Omit(cols ...field.Expr) IEventSetStartBlockDo
	Join(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo
	Group(cols ...field.Expr) IEventSetStartBlockDo
	Having(conds ...gen.Condition) IEventSetStartBlockDo
	Limit(limit int) IEventSetStartBlockDo
	Offset(offset int) IEventSetStartBlockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetStartBlockDo
	Unscoped() IEventSetStartBlockDo
	Create(values ...*model.EventSetStartBlock) error
	CreateInBatches(values []*model.EventSetStartBlock, batchSize int) error
	Save(values ...*model.EventSetStartBlock) error
	First() (*model.EventSetStartBlock, error)
	Take() (*model.EventSetStartBlock, error)
	Last() (*model.EventSetStartBlock, error)
	Find() ([]*model.EventSetStartBlock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetStartBlock, err error)
	FindInBatches(result *[]*model.EventSetStartBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventSetStartBlock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventSetStartBlockDo
	Assign(attrs ...field.AssignExpr) IEventSetStartBlockDo
	Joins(fields ...field.RelationField) IEventSetStartBlockDo
	Preload(fields ...field.RelationField) IEventSetStartBlockDo
	FirstOrInit() (*model.EventSetStartBlock, error)
	FirstOrCreate() (*model.EventSetStartBlock, error)
	FindByPage(offset int, limit int) (result []*model.EventSetStartBlock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventSetStartBlockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventSetStartBlockDo) Debug() IEventSetStartBlockDo {
	return e.withDO(e.DO.Debug())
}

func (e eventSetStartBlockDo) WithContext(ctx context.Context) IEventSetStartBlockDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventSetStartBlockDo) ReadDB() IEventSetStartBlockDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventSetStartBlockDo) WriteDB() IEventSetStartBlockDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventSetStartBlockDo) Session(config *gorm.Session) IEventSetStartBlockDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventSetStartBlockDo) Clauses(conds ...clause.Expression) IEventSetStartBlockDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventSetStartBlockDo) Returning(value interface{}, columns ...string) IEventSetStartBlockDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventSetStartBlockDo) Not(conds ...gen.Condition) IEventSetStartBlockDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventSetStartBlockDo) Or(conds ...gen.Condition) IEventSetStartBlockDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventSetStartBlockDo) Select(conds ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventSetStartBlockDo) Where(conds ...gen.Condition) IEventSetStartBlockDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventSetStartBlockDo) Order(conds ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventSetStartBlockDo) Distinct(cols ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventSetStartBlockDo) Omit(cols ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventSetStartBlockDo) Join(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventSetStartBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventSetStartBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventSetStartBlockDo) Group(cols ...field.Expr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventSetStartBlockDo) Having(conds ...gen.Condition) IEventSetStartBlockDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventSetStartBlockDo) Limit(limit int) IEventSetStartBlockDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventSetStartBlockDo) Offset(offset int) IEventSetStartBlockDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventSetStartBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetStartBlockDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventSetStartBlockDo) Unscoped() IEventSetStartBlockDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventSetStartBlockDo) Create(values ...*model.EventSetStartBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventSetStartBlockDo) CreateInBatches(values []*model.EventSetStartBlock, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventSetStartBlockDo) Save(values ...*model.EventSetStartBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventSetStartBlockDo) First() (*model.EventSetStartBlock, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetStartBlock), nil
	}
}

func (e eventSetStartBlockDo) Take() (*model.EventSetStartBlock, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetStartBlock), nil
	}
}

func (e eventSetStartBlockDo) Last() (*model.EventSetStartBlock, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetStartBlock), nil
	}
}

func (e eventSetStartBlockDo) Find() ([]*model.EventSetStartBlock, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventSetStartBlock), err
}

func (e eventSetStartBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetStartBlock, err error) {
	buf := make([]*model.EventSetStartBlock, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventSetStartBlockDo) FindInBatches(result *[]*model.EventSetStartBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventSetStartBlockDo) Attrs(attrs ...field.AssignExpr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventSetStartBlockDo) Assign(attrs ...field.AssignExpr) IEventSetStartBlockDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventSetStartBlockDo) Joins(fields ...field.RelationField) IEventSetStartBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventSetStartBlockDo) Preload(fields ...field.RelationField) IEventSetStartBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventSetStartBlockDo) FirstOrInit() (*model.EventSetStartBlock, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetStartBlock), nil
	}
}

func (e eventSetStartBlockDo) FirstOrCreate() (*model.EventSetStartBlock, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetStartBlock), nil
	}
}

func (e eventSetStartBlockDo) FindByPage(offset int, limit int) (result []*model.EventSetStartBlock, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventSetStartBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventSetStartBlockDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventSetStartBlockDo) Delete(models ...*model.EventSetStartBlock) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventSetStartBlockDo) withDO(do gen.Dao) *eventSetStartBlockDo {
	e.DO = *do.(*gen.DO)
	return e
}
