// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventSetMetanode(db *gorm.DB, opts ...gen.DOOption) eventSetMetanode {
	_eventSetMetanode := eventSetMetanode{}

	_eventSetMetanode.eventSetMetanodeDo.UseDB(db, opts...)
	_eventSetMetanode.eventSetMetanodeDo.UseModel(&model.EventSetMetanode{})

	tableName := _eventSetMetanode.eventSetMetanodeDo.TableName()
	_eventSetMetanode.ALL = field.NewAsterisk(tableName)
	_eventSetMetanode.ID = field.NewInt64(tableName, "id")
	_eventSetMetanode.ContractAddress = field.NewString(tableName, "contract_address")
	_eventSetMetanode.MetanodeToken = field.NewString(tableName, "metanode_token")
	_eventSetMetanode.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventSetMetanode.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventSetMetanode.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventSetMetanode.LogIndex = field.NewInt32(tableName, "log_index")
	_eventSetMetanode.CreatedAt = field.NewTime(tableName, "created_at")

	_eventSetMetanode.fillFieldMap()

	return _eventSetMetanode
}

// eventSetMetanode SetMetaNode事件表
type eventSetMetanode struct {
	eventSetMetanodeDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	MetanodeToken   field.String // MetaNode代币地址
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventSetMetanode) Table(newTableName string) *eventSetMetanode {
	e.eventSetMetanodeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventSetMetanode) As(alias string) *eventSetMetanode {
	e.eventSetMetanodeDo.DO = *(e.eventSetMetanodeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventSetMetanode) updateTableName(table string) *eventSetMetanode {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.MetanodeToken = field.NewString(table, "metanode_token")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventSetMetanode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventSetMetanode) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["metanode_token"] = e.MetanodeToken
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventSetMetanode) clone(db *gorm.DB) eventSetMetanode {
	e.eventSetMetanodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventSetMetanode) replaceDB(db *gorm.DB) eventSetMetanode {
	e.eventSetMetanodeDo.ReplaceDB(db)
	return e
}

type eventSetMetanodeDo struct{ gen.DO }

type IEventSetMetanodeDo interface {
	gen.SubQuery
	Debug() IEventSetMetanodeDo
	WithContext(ctx context.Context) IEventSetMetanodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventSetMetanodeDo
	WriteDB() IEventSetMetanodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventSetMetanodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventSetMetanodeDo
	Not(conds ...gen.Condition) IEventSetMetanodeDo
	Or(conds ...gen.Condition) IEventSetMetanodeDo
	Select(conds ...field.Expr) IEventSetMetanodeDo
	Where(conds ...gen.Condition) IEventSetMetanodeDo
	Order(conds ...field.Expr) IEventSetMetanodeDo
	Distinct(cols ...field.Expr) IEventSetMetanodeDo
	Omit(cols ...field.Expr) IEventSetMetanodeDo
	Join(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo
	Group(cols ...field.Expr) IEventSetMetanodeDo
	Having(conds ...gen.Condition) IEventSetMetanodeDo
	Limit(limit int) IEventSetMetanodeDo
	Offset(offset int) IEventSetMetanodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetMetanodeDo
	Unscoped() IEventSetMetanodeDo
	Create(values ...*model.EventSetMetanode) error
	CreateInBatches(values []*model.EventSetMetanode, batchSize int) error
	Save(values ...*model.EventSetMetanode) error
	First() (*model.EventSetMetanode, error)
	Take() (*model.EventSetMetanode, error)
	Last() (*model.EventSetMetanode, error)
	Find() ([]*model.EventSetMetanode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetMetanode, err error)
	FindInBatches(result *[]*model.EventSetMetanode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventSetMetanode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventSetMetanodeDo
	Assign(attrs ...field.AssignExpr) IEventSetMetanodeDo
	Joins(fields ...field.RelationField) IEventSetMetanodeDo
	Preload(fields ...field.RelationField) IEventSetMetanodeDo
	FirstOrInit() (*model.EventSetMetanode, error)
	FirstOrCreate() (*model.EventSetMetanode, error)
	FindByPage(offset int, limit int) (result []*model.EventSetMetanode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventSetMetanodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventSetMetanodeDo) Debug() IEventSetMetanodeDo {
	return e.withDO(e.DO.Debug())
}

func (e eventSetMetanodeDo) WithContext(ctx context.Context) IEventSetMetanodeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventSetMetanodeDo) ReadDB() IEventSetMetanodeDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventSetMetanodeDo) WriteDB() IEventSetMetanodeDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventSetMetanodeDo) Session(config *gorm.Session) IEventSetMetanodeDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventSetMetanodeDo) Clauses(conds ...clause.Expression) IEventSetMetanodeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventSetMetanodeDo) Returning(value interface{}, columns ...string) IEventSetMetanodeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventSetMetanodeDo) Not(conds ...gen.Condition) IEventSetMetanodeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventSetMetanodeDo) Or(conds ...gen.Condition) IEventSetMetanodeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventSetMetanodeDo) Select(conds ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventSetMetanodeDo) Where(conds ...gen.Condition) IEventSetMetanodeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventSetMetanodeDo) Order(conds ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventSetMetanodeDo) Distinct(cols ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventSetMetanodeDo) Omit(cols ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventSetMetanodeDo) Join(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventSetMetanodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventSetMetanodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventSetMetanodeDo) Group(cols ...field.Expr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventSetMetanodeDo) Having(conds ...gen.Condition) IEventSetMetanodeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventSetMetanodeDo) Limit(limit int) IEventSetMetanodeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventSetMetanodeDo) Offset(offset int) IEventSetMetanodeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventSetMetanodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetMetanodeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventSetMetanodeDo) Unscoped() IEventSetMetanodeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventSetMetanodeDo) Create(values ...*model.EventSetMetanode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventSetMetanodeDo) CreateInBatches(values []*model.EventSetMetanode, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventSetMetanodeDo) Save(values ...*model.EventSetMetanode) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventSetMetanodeDo) First() (*model.EventSetMetanode, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanode), nil
	}
}

func (e eventSetMetanodeDo) Take() (*model.EventSetMetanode, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanode), nil
	}
}

func (e eventSetMetanodeDo) Last() (*model.EventSetMetanode, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanode), nil
	}
}

func (e eventSetMetanodeDo) Find() ([]*model.EventSetMetanode, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventSetMetanode), err
}

func (e eventSetMetanodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetMetanode, err error) {
	buf := make([]*model.EventSetMetanode, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventSetMetanodeDo) FindInBatches(result *[]*model.EventSetMetanode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventSetMetanodeDo) Attrs(attrs ...field.AssignExpr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventSetMetanodeDo) Assign(attrs ...field.AssignExpr) IEventSetMetanodeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventSetMetanodeDo) Joins(fields ...field.RelationField) IEventSetMetanodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventSetMetanodeDo) Preload(fields ...field.RelationField) IEventSetMetanodeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventSetMetanodeDo) FirstOrInit() (*model.EventSetMetanode, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanode), nil
	}
}

func (e eventSetMetanodeDo) FirstOrCreate() (*model.EventSetMetanode, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanode), nil
	}
}

func (e eventSetMetanodeDo) FindByPage(offset int, limit int) (result []*model.EventSetMetanode, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventSetMetanodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventSetMetanodeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventSetMetanodeDo) Delete(models ...*model.EventSetMetanode) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventSetMetanodeDo) withDO(do gen.Dao) *eventSetMetanodeDo {
	e.DO = *do.(*gen.DO)
	return e
}
