// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventSetEndBlock(db *gorm.DB, opts ...gen.DOOption) eventSetEndBlock {
	_eventSetEndBlock := eventSetEndBlock{}

	_eventSetEndBlock.eventSetEndBlockDo.UseDB(db, opts...)
	_eventSetEndBlock.eventSetEndBlockDo.UseModel(&model.EventSetEndBlock{})

	tableName := _eventSetEndBlock.eventSetEndBlockDo.TableName()
	_eventSetEndBlock.ALL = field.NewAsterisk(tableName)
	_eventSetEndBlock.ID = field.NewInt64(tableName, "id")
	_eventSetEndBlock.ContractAddress = field.NewString(tableName, "contract_address")
	_eventSetEndBlock.EndBlock = field.NewUint64(tableName, "end_block")
	_eventSetEndBlock.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventSetEndBlock.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventSetEndBlock.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventSetEndBlock.LogIndex = field.NewInt32(tableName, "log_index")
	_eventSetEndBlock.CreatedAt = field.NewTime(tableName, "created_at")

	_eventSetEndBlock.fillFieldMap()

	return _eventSetEndBlock
}

// eventSetEndBlock 设置结束区块事件表
type eventSetEndBlock struct {
	eventSetEndBlockDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	EndBlock        field.Uint64 // 质押结束区块
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventSetEndBlock) Table(newTableName string) *eventSetEndBlock {
	e.eventSetEndBlockDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventSetEndBlock) As(alias string) *eventSetEndBlock {
	e.eventSetEndBlockDo.DO = *(e.eventSetEndBlockDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventSetEndBlock) updateTableName(table string) *eventSetEndBlock {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.EndBlock = field.NewUint64(table, "end_block")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventSetEndBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventSetEndBlock) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["end_block"] = e.EndBlock
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventSetEndBlock) clone(db *gorm.DB) eventSetEndBlock {
	e.eventSetEndBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventSetEndBlock) replaceDB(db *gorm.DB) eventSetEndBlock {
	e.eventSetEndBlockDo.ReplaceDB(db)
	return e
}

type eventSetEndBlockDo struct{ gen.DO }

type IEventSetEndBlockDo interface {
	gen.SubQuery
	Debug() IEventSetEndBlockDo
	WithContext(ctx context.Context) IEventSetEndBlockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventSetEndBlockDo
	WriteDB() IEventSetEndBlockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventSetEndBlockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventSetEndBlockDo
	Not(conds ...gen.Condition) IEventSetEndBlockDo
	Or(conds ...gen.Condition) IEventSetEndBlockDo
	Select(conds ...field.Expr) IEventSetEndBlockDo
	Where(conds ...gen.Condition) IEventSetEndBlockDo
	Order(conds ...field.Expr) IEventSetEndBlockDo
	Distinct(cols ...field.Expr) IEventSetEndBlockDo
	Omit(cols ...field.Expr) IEventSetEndBlockDo
	Join(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo
	Group(cols ...field.Expr) IEventSetEndBlockDo
	Having(conds ...gen.Condition) IEventSetEndBlockDo
	Limit(limit int) IEventSetEndBlockDo
	Offset(offset int) IEventSetEndBlockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetEndBlockDo
	Unscoped() IEventSetEndBlockDo
	Create(values ...*model.EventSetEndBlock) error
	CreateInBatches(values []*model.EventSetEndBlock, batchSize int) error
	Save(values ...*model.EventSetEndBlock) error
	First() (*model.EventSetEndBlock, error)
	Take() (*model.EventSetEndBlock, error)
	Last() (*model.EventSetEndBlock, error)
	Find() ([]*model.EventSetEndBlock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetEndBlock, err error)
	FindInBatches(result *[]*model.EventSetEndBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventSetEndBlock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventSetEndBlockDo
	Assign(attrs ...field.AssignExpr) IEventSetEndBlockDo
	Joins(fields ...field.RelationField) IEventSetEndBlockDo
	Preload(fields ...field.RelationField) IEventSetEndBlockDo
	FirstOrInit() (*model.EventSetEndBlock, error)
	FirstOrCreate() (*model.EventSetEndBlock, error)
	FindByPage(offset int, limit int) (result []*model.EventSetEndBlock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventSetEndBlockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventSetEndBlockDo) Debug() IEventSetEndBlockDo {
	return e.withDO(e.DO.Debug())
}

func (e eventSetEndBlockDo) WithContext(ctx context.Context) IEventSetEndBlockDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventSetEndBlockDo) ReadDB() IEventSetEndBlockDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventSetEndBlockDo) WriteDB() IEventSetEndBlockDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventSetEndBlockDo) Session(config *gorm.Session) IEventSetEndBlockDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventSetEndBlockDo) Clauses(conds ...clause.Expression) IEventSetEndBlockDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventSetEndBlockDo) Returning(value interface{}, columns ...string) IEventSetEndBlockDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventSetEndBlockDo) Not(conds ...gen.Condition) IEventSetEndBlockDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventSetEndBlockDo) Or(conds ...gen.Condition) IEventSetEndBlockDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventSetEndBlockDo) Select(conds ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventSetEndBlockDo) Where(conds ...gen.Condition) IEventSetEndBlockDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventSetEndBlockDo) Order(conds ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventSetEndBlockDo) Distinct(cols ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventSetEndBlockDo) Omit(cols ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventSetEndBlockDo) Join(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventSetEndBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventSetEndBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventSetEndBlockDo) Group(cols ...field.Expr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventSetEndBlockDo) Having(conds ...gen.Condition) IEventSetEndBlockDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventSetEndBlockDo) Limit(limit int) IEventSetEndBlockDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventSetEndBlockDo) Offset(offset int) IEventSetEndBlockDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventSetEndBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetEndBlockDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventSetEndBlockDo) Unscoped() IEventSetEndBlockDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventSetEndBlockDo) Create(values ...*model.EventSetEndBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventSetEndBlockDo) CreateInBatches(values []*model.EventSetEndBlock, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventSetEndBlockDo) Save(values ...*model.EventSetEndBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventSetEndBlockDo) First() (*model.EventSetEndBlock, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetEndBlock), nil
	}
}

func (e eventSetEndBlockDo) Take() (*model.EventSetEndBlock, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetEndBlock), nil
	}
}

func (e eventSetEndBlockDo) Last() (*model.EventSetEndBlock, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetEndBlock), nil
	}
}

func (e eventSetEndBlockDo) Find() ([]*model.EventSetEndBlock, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventSetEndBlock), err
}

func (e eventSetEndBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetEndBlock, err error) {
	buf := make([]*model.EventSetEndBlock, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventSetEndBlockDo) FindInBatches(result *[]*model.EventSetEndBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventSetEndBlockDo) Attrs(attrs ...field.AssignExpr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventSetEndBlockDo) Assign(attrs ...field.AssignExpr) IEventSetEndBlockDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventSetEndBlockDo) Joins(fields ...field.RelationField) IEventSetEndBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventSetEndBlockDo) Preload(fields ...field.RelationField) IEventSetEndBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventSetEndBlockDo) FirstOrInit() (*model.EventSetEndBlock, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetEndBlock), nil
	}
}

func (e eventSetEndBlockDo) FirstOrCreate() (*model.EventSetEndBlock, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetEndBlock), nil
	}
}

func (e eventSetEndBlockDo) FindByPage(offset int, limit int) (result []*model.EventSetEndBlock, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventSetEndBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventSetEndBlockDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventSetEndBlockDo) Delete(models ...*model.EventSetEndBlock) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventSetEndBlockDo) withDO(do gen.Dao) *eventSetEndBlockDo {
	e.DO = *do.(*gen.DO)
	return e
}
