// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventSetPoolWeight(db *gorm.DB, opts ...gen.DOOption) eventSetPoolWeight {
	_eventSetPoolWeight := eventSetPoolWeight{}

	_eventSetPoolWeight.eventSetPoolWeightDo.UseDB(db, opts...)
	_eventSetPoolWeight.eventSetPoolWeightDo.UseModel(&model.EventSetPoolWeight{})

	tableName := _eventSetPoolWeight.eventSetPoolWeightDo.TableName()
	_eventSetPoolWeight.ALL = field.NewAsterisk(tableName)
	_eventSetPoolWeight.ID = field.NewInt64(tableName, "id")
	_eventSetPoolWeight.ContractAddress = field.NewString(tableName, "contract_address")
	_eventSetPoolWeight.PoolID = field.NewInt32(tableName, "pool_id")
	_eventSetPoolWeight.PoolWeight = field.NewFloat64(tableName, "pool_weight")
	_eventSetPoolWeight.TotalPoolWeight = field.NewFloat64(tableName, "total_pool_weight")
	_eventSetPoolWeight.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventSetPoolWeight.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventSetPoolWeight.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventSetPoolWeight.LogIndex = field.NewInt32(tableName, "log_index")
	_eventSetPoolWeight.CreatedAt = field.NewTime(tableName, "created_at")

	_eventSetPoolWeight.fillFieldMap()

	return _eventSetPoolWeight
}

// eventSetPoolWeight 设置资金池权重事件表
type eventSetPoolWeight struct {
	eventSetPoolWeightDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	PoolID          field.Int32   // 资金池ID
	PoolWeight      field.Float64 // 新的资金池权重
	TotalPoolWeight field.Float64 // 所有池的总权重
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventSetPoolWeight) Table(newTableName string) *eventSetPoolWeight {
	e.eventSetPoolWeightDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventSetPoolWeight) As(alias string) *eventSetPoolWeight {
	e.eventSetPoolWeightDo.DO = *(e.eventSetPoolWeightDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventSetPoolWeight) updateTableName(table string) *eventSetPoolWeight {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.PoolWeight = field.NewFloat64(table, "pool_weight")
	e.TotalPoolWeight = field.NewFloat64(table, "total_pool_weight")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventSetPoolWeight) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventSetPoolWeight) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["pool_weight"] = e.PoolWeight
	e.fieldMap["total_pool_weight"] = e.TotalPoolWeight
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventSetPoolWeight) clone(db *gorm.DB) eventSetPoolWeight {
	e.eventSetPoolWeightDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventSetPoolWeight) replaceDB(db *gorm.DB) eventSetPoolWeight {
	e.eventSetPoolWeightDo.ReplaceDB(db)
	return e
}

type eventSetPoolWeightDo struct{ gen.DO }

type IEventSetPoolWeightDo interface {
	gen.SubQuery
	Debug() IEventSetPoolWeightDo
	WithContext(ctx context.Context) IEventSetPoolWeightDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventSetPoolWeightDo
	WriteDB() IEventSetPoolWeightDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventSetPoolWeightDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventSetPoolWeightDo
	Not(conds ...gen.Condition) IEventSetPoolWeightDo
	Or(conds ...gen.Condition) IEventSetPoolWeightDo
	Select(conds ...field.Expr) IEventSetPoolWeightDo
	Where(conds ...gen.Condition) IEventSetPoolWeightDo
	Order(conds ...field.Expr) IEventSetPoolWeightDo
	Distinct(cols ...field.Expr) IEventSetPoolWeightDo
	Omit(cols ...field.Expr) IEventSetPoolWeightDo
	Join(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo
	Group(cols ...field.Expr) IEventSetPoolWeightDo
	Having(conds ...gen.Condition) IEventSetPoolWeightDo
	Limit(limit int) IEventSetPoolWeightDo
	Offset(offset int) IEventSetPoolWeightDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetPoolWeightDo
	Unscoped() IEventSetPoolWeightDo
	Create(values ...*model.EventSetPoolWeight) error
	CreateInBatches(values []*model.EventSetPoolWeight, batchSize int) error
	Save(values ...*model.EventSetPoolWeight) error
	First() (*model.EventSetPoolWeight, error)
	Take() (*model.EventSetPoolWeight, error)
	Last() (*model.EventSetPoolWeight, error)
	Find() ([]*model.EventSetPoolWeight, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetPoolWeight, err error)
	FindInBatches(result *[]*model.EventSetPoolWeight, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventSetPoolWeight) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventSetPoolWeightDo
	Assign(attrs ...field.AssignExpr) IEventSetPoolWeightDo
	Joins(fields ...field.RelationField) IEventSetPoolWeightDo
	Preload(fields ...field.RelationField) IEventSetPoolWeightDo
	FirstOrInit() (*model.EventSetPoolWeight, error)
	FirstOrCreate() (*model.EventSetPoolWeight, error)
	FindByPage(offset int, limit int) (result []*model.EventSetPoolWeight, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventSetPoolWeightDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventSetPoolWeightDo) Debug() IEventSetPoolWeightDo {
	return e.withDO(e.DO.Debug())
}

func (e eventSetPoolWeightDo) WithContext(ctx context.Context) IEventSetPoolWeightDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventSetPoolWeightDo) ReadDB() IEventSetPoolWeightDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventSetPoolWeightDo) WriteDB() IEventSetPoolWeightDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventSetPoolWeightDo) Session(config *gorm.Session) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventSetPoolWeightDo) Clauses(conds ...clause.Expression) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventSetPoolWeightDo) Returning(value interface{}, columns ...string) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventSetPoolWeightDo) Not(conds ...gen.Condition) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventSetPoolWeightDo) Or(conds ...gen.Condition) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventSetPoolWeightDo) Select(conds ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventSetPoolWeightDo) Where(conds ...gen.Condition) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventSetPoolWeightDo) Order(conds ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventSetPoolWeightDo) Distinct(cols ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventSetPoolWeightDo) Omit(cols ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventSetPoolWeightDo) Join(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventSetPoolWeightDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventSetPoolWeightDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventSetPoolWeightDo) Group(cols ...field.Expr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventSetPoolWeightDo) Having(conds ...gen.Condition) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventSetPoolWeightDo) Limit(limit int) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventSetPoolWeightDo) Offset(offset int) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventSetPoolWeightDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventSetPoolWeightDo) Unscoped() IEventSetPoolWeightDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventSetPoolWeightDo) Create(values ...*model.EventSetPoolWeight) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventSetPoolWeightDo) CreateInBatches(values []*model.EventSetPoolWeight, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventSetPoolWeightDo) Save(values ...*model.EventSetPoolWeight) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventSetPoolWeightDo) First() (*model.EventSetPoolWeight, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetPoolWeight), nil
	}
}

func (e eventSetPoolWeightDo) Take() (*model.EventSetPoolWeight, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetPoolWeight), nil
	}
}

func (e eventSetPoolWeightDo) Last() (*model.EventSetPoolWeight, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetPoolWeight), nil
	}
}

func (e eventSetPoolWeightDo) Find() ([]*model.EventSetPoolWeight, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventSetPoolWeight), err
}

func (e eventSetPoolWeightDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetPoolWeight, err error) {
	buf := make([]*model.EventSetPoolWeight, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventSetPoolWeightDo) FindInBatches(result *[]*model.EventSetPoolWeight, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventSetPoolWeightDo) Attrs(attrs ...field.AssignExpr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventSetPoolWeightDo) Assign(attrs ...field.AssignExpr) IEventSetPoolWeightDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventSetPoolWeightDo) Joins(fields ...field.RelationField) IEventSetPoolWeightDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventSetPoolWeightDo) Preload(fields ...field.RelationField) IEventSetPoolWeightDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventSetPoolWeightDo) FirstOrInit() (*model.EventSetPoolWeight, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetPoolWeight), nil
	}
}

func (e eventSetPoolWeightDo) FirstOrCreate() (*model.EventSetPoolWeight, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetPoolWeight), nil
	}
}

func (e eventSetPoolWeightDo) FindByPage(offset int, limit int) (result []*model.EventSetPoolWeight, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventSetPoolWeightDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventSetPoolWeightDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventSetPoolWeightDo) Delete(models ...*model.EventSetPoolWeight) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventSetPoolWeightDo) withDO(do gen.Dao) *eventSetPoolWeightDo {
	e.DO = *do.(*gen.DO)
	return e
}
