// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventSetMetanodePerBlock(db *gorm.DB, opts ...gen.DOOption) eventSetMetanodePerBlock {
	_eventSetMetanodePerBlock := eventSetMetanodePerBlock{}

	_eventSetMetanodePerBlock.eventSetMetanodePerBlockDo.UseDB(db, opts...)
	_eventSetMetanodePerBlock.eventSetMetanodePerBlockDo.UseModel(&model.EventSetMetanodePerBlock{})

	tableName := _eventSetMetanodePerBlock.eventSetMetanodePerBlockDo.TableName()
	_eventSetMetanodePerBlock.ALL = field.NewAsterisk(tableName)
	_eventSetMetanodePerBlock.ID = field.NewInt64(tableName, "id")
	_eventSetMetanodePerBlock.ContractAddress = field.NewString(tableName, "contract_address")
	_eventSetMetanodePerBlock.MetanodePerBlock = field.NewFloat64(tableName, "metanode_per_block")
	_eventSetMetanodePerBlock.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventSetMetanodePerBlock.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventSetMetanodePerBlock.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventSetMetanodePerBlock.LogIndex = field.NewInt32(tableName, "log_index")
	_eventSetMetanodePerBlock.CreatedAt = field.NewTime(tableName, "created_at")

	_eventSetMetanodePerBlock.fillFieldMap()

	return _eventSetMetanodePerBlock
}

// eventSetMetanodePerBlock 设置每区块奖励事件表
type eventSetMetanodePerBlock struct {
	eventSetMetanodePerBlockDo

	ALL              field.Asterisk
	ID               field.Int64
	ContractAddress  field.String
	MetanodePerBlock field.Float64 // 每区块MetaNode奖励
	BlockNumber      field.Uint64
	BlockTimestamp   field.Uint64
	TransactionHash  field.String
	LogIndex         field.Int32
	CreatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (e eventSetMetanodePerBlock) Table(newTableName string) *eventSetMetanodePerBlock {
	e.eventSetMetanodePerBlockDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventSetMetanodePerBlock) As(alias string) *eventSetMetanodePerBlock {
	e.eventSetMetanodePerBlockDo.DO = *(e.eventSetMetanodePerBlockDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventSetMetanodePerBlock) updateTableName(table string) *eventSetMetanodePerBlock {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.MetanodePerBlock = field.NewFloat64(table, "metanode_per_block")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventSetMetanodePerBlock) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventSetMetanodePerBlock) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 8)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["metanode_per_block"] = e.MetanodePerBlock
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventSetMetanodePerBlock) clone(db *gorm.DB) eventSetMetanodePerBlock {
	e.eventSetMetanodePerBlockDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventSetMetanodePerBlock) replaceDB(db *gorm.DB) eventSetMetanodePerBlock {
	e.eventSetMetanodePerBlockDo.ReplaceDB(db)
	return e
}

type eventSetMetanodePerBlockDo struct{ gen.DO }

type IEventSetMetanodePerBlockDo interface {
	gen.SubQuery
	Debug() IEventSetMetanodePerBlockDo
	WithContext(ctx context.Context) IEventSetMetanodePerBlockDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventSetMetanodePerBlockDo
	WriteDB() IEventSetMetanodePerBlockDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventSetMetanodePerBlockDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventSetMetanodePerBlockDo
	Not(conds ...gen.Condition) IEventSetMetanodePerBlockDo
	Or(conds ...gen.Condition) IEventSetMetanodePerBlockDo
	Select(conds ...field.Expr) IEventSetMetanodePerBlockDo
	Where(conds ...gen.Condition) IEventSetMetanodePerBlockDo
	Order(conds ...field.Expr) IEventSetMetanodePerBlockDo
	Distinct(cols ...field.Expr) IEventSetMetanodePerBlockDo
	Omit(cols ...field.Expr) IEventSetMetanodePerBlockDo
	Join(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo
	Group(cols ...field.Expr) IEventSetMetanodePerBlockDo
	Having(conds ...gen.Condition) IEventSetMetanodePerBlockDo
	Limit(limit int) IEventSetMetanodePerBlockDo
	Offset(offset int) IEventSetMetanodePerBlockDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetMetanodePerBlockDo
	Unscoped() IEventSetMetanodePerBlockDo
	Create(values ...*model.EventSetMetanodePerBlock) error
	CreateInBatches(values []*model.EventSetMetanodePerBlock, batchSize int) error
	Save(values ...*model.EventSetMetanodePerBlock) error
	First() (*model.EventSetMetanodePerBlock, error)
	Take() (*model.EventSetMetanodePerBlock, error)
	Last() (*model.EventSetMetanodePerBlock, error)
	Find() ([]*model.EventSetMetanodePerBlock, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetMetanodePerBlock, err error)
	FindInBatches(result *[]*model.EventSetMetanodePerBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventSetMetanodePerBlock) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventSetMetanodePerBlockDo
	Assign(attrs ...field.AssignExpr) IEventSetMetanodePerBlockDo
	Joins(fields ...field.RelationField) IEventSetMetanodePerBlockDo
	Preload(fields ...field.RelationField) IEventSetMetanodePerBlockDo
	FirstOrInit() (*model.EventSetMetanodePerBlock, error)
	FirstOrCreate() (*model.EventSetMetanodePerBlock, error)
	FindByPage(offset int, limit int) (result []*model.EventSetMetanodePerBlock, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventSetMetanodePerBlockDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventSetMetanodePerBlockDo) Debug() IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Debug())
}

func (e eventSetMetanodePerBlockDo) WithContext(ctx context.Context) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventSetMetanodePerBlockDo) ReadDB() IEventSetMetanodePerBlockDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventSetMetanodePerBlockDo) WriteDB() IEventSetMetanodePerBlockDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventSetMetanodePerBlockDo) Session(config *gorm.Session) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventSetMetanodePerBlockDo) Clauses(conds ...clause.Expression) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventSetMetanodePerBlockDo) Returning(value interface{}, columns ...string) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventSetMetanodePerBlockDo) Not(conds ...gen.Condition) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventSetMetanodePerBlockDo) Or(conds ...gen.Condition) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventSetMetanodePerBlockDo) Select(conds ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventSetMetanodePerBlockDo) Where(conds ...gen.Condition) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventSetMetanodePerBlockDo) Order(conds ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventSetMetanodePerBlockDo) Distinct(cols ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventSetMetanodePerBlockDo) Omit(cols ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventSetMetanodePerBlockDo) Join(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventSetMetanodePerBlockDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventSetMetanodePerBlockDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventSetMetanodePerBlockDo) Group(cols ...field.Expr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventSetMetanodePerBlockDo) Having(conds ...gen.Condition) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventSetMetanodePerBlockDo) Limit(limit int) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventSetMetanodePerBlockDo) Offset(offset int) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventSetMetanodePerBlockDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventSetMetanodePerBlockDo) Unscoped() IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventSetMetanodePerBlockDo) Create(values ...*model.EventSetMetanodePerBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventSetMetanodePerBlockDo) CreateInBatches(values []*model.EventSetMetanodePerBlock, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventSetMetanodePerBlockDo) Save(values ...*model.EventSetMetanodePerBlock) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventSetMetanodePerBlockDo) First() (*model.EventSetMetanodePerBlock, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanodePerBlock), nil
	}
}

func (e eventSetMetanodePerBlockDo) Take() (*model.EventSetMetanodePerBlock, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanodePerBlock), nil
	}
}

func (e eventSetMetanodePerBlockDo) Last() (*model.EventSetMetanodePerBlock, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanodePerBlock), nil
	}
}

func (e eventSetMetanodePerBlockDo) Find() ([]*model.EventSetMetanodePerBlock, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventSetMetanodePerBlock), err
}

func (e eventSetMetanodePerBlockDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventSetMetanodePerBlock, err error) {
	buf := make([]*model.EventSetMetanodePerBlock, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventSetMetanodePerBlockDo) FindInBatches(result *[]*model.EventSetMetanodePerBlock, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventSetMetanodePerBlockDo) Attrs(attrs ...field.AssignExpr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventSetMetanodePerBlockDo) Assign(attrs ...field.AssignExpr) IEventSetMetanodePerBlockDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventSetMetanodePerBlockDo) Joins(fields ...field.RelationField) IEventSetMetanodePerBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventSetMetanodePerBlockDo) Preload(fields ...field.RelationField) IEventSetMetanodePerBlockDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventSetMetanodePerBlockDo) FirstOrInit() (*model.EventSetMetanodePerBlock, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanodePerBlock), nil
	}
}

func (e eventSetMetanodePerBlockDo) FirstOrCreate() (*model.EventSetMetanodePerBlock, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventSetMetanodePerBlock), nil
	}
}

func (e eventSetMetanodePerBlockDo) FindByPage(offset int, limit int) (result []*model.EventSetMetanodePerBlock, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventSetMetanodePerBlockDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventSetMetanodePerBlockDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventSetMetanodePerBlockDo) Delete(models ...*model.EventSetMetanodePerBlock) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventSetMetanodePerBlockDo) withDO(do gen.Dao) *eventSetMetanodePerBlockDo {
	e.DO = *do.(*gen.DO)
	return e
}
