// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventRequestUnstake(db *gorm.DB, opts ...gen.DOOption) eventRequestUnstake {
	_eventRequestUnstake := eventRequestUnstake{}

	_eventRequestUnstake.eventRequestUnstakeDo.UseDB(db, opts...)
	_eventRequestUnstake.eventRequestUnstakeDo.UseModel(&model.EventRequestUnstake{})

	tableName := _eventRequestUnstake.eventRequestUnstakeDo.TableName()
	_eventRequestUnstake.ALL = field.NewAsterisk(tableName)
	_eventRequestUnstake.ID = field.NewInt64(tableName, "id")
	_eventRequestUnstake.ContractAddress = field.NewString(tableName, "contract_address")
	_eventRequestUnstake.UserAddress = field.NewString(tableName, "user_address")
	_eventRequestUnstake.PoolID = field.NewInt32(tableName, "pool_id")
	_eventRequestUnstake.Amount = field.NewFloat64(tableName, "amount")
	_eventRequestUnstake.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventRequestUnstake.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventRequestUnstake.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventRequestUnstake.LogIndex = field.NewInt32(tableName, "log_index")
	_eventRequestUnstake.CreatedAt = field.NewTime(tableName, "created_at")

	_eventRequestUnstake.fillFieldMap()

	return _eventRequestUnstake
}

// eventRequestUnstake 申请解质押事件表
type eventRequestUnstake struct {
	eventRequestUnstakeDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	UserAddress     field.String  // 用户地址
	PoolID          field.Int32   // 资金池ID
	Amount          field.Float64 // 解质押金额
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventRequestUnstake) Table(newTableName string) *eventRequestUnstake {
	e.eventRequestUnstakeDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventRequestUnstake) As(alias string) *eventRequestUnstake {
	e.eventRequestUnstakeDo.DO = *(e.eventRequestUnstakeDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventRequestUnstake) updateTableName(table string) *eventRequestUnstake {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.UserAddress = field.NewString(table, "user_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.Amount = field.NewFloat64(table, "amount")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventRequestUnstake) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventRequestUnstake) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["user_address"] = e.UserAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["amount"] = e.Amount
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventRequestUnstake) clone(db *gorm.DB) eventRequestUnstake {
	e.eventRequestUnstakeDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventRequestUnstake) replaceDB(db *gorm.DB) eventRequestUnstake {
	e.eventRequestUnstakeDo.ReplaceDB(db)
	return e
}

type eventRequestUnstakeDo struct{ gen.DO }

type IEventRequestUnstakeDo interface {
	gen.SubQuery
	Debug() IEventRequestUnstakeDo
	WithContext(ctx context.Context) IEventRequestUnstakeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventRequestUnstakeDo
	WriteDB() IEventRequestUnstakeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventRequestUnstakeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventRequestUnstakeDo
	Not(conds ...gen.Condition) IEventRequestUnstakeDo
	Or(conds ...gen.Condition) IEventRequestUnstakeDo
	Select(conds ...field.Expr) IEventRequestUnstakeDo
	Where(conds ...gen.Condition) IEventRequestUnstakeDo
	Order(conds ...field.Expr) IEventRequestUnstakeDo
	Distinct(cols ...field.Expr) IEventRequestUnstakeDo
	Omit(cols ...field.Expr) IEventRequestUnstakeDo
	Join(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo
	Group(cols ...field.Expr) IEventRequestUnstakeDo
	Having(conds ...gen.Condition) IEventRequestUnstakeDo
	Limit(limit int) IEventRequestUnstakeDo
	Offset(offset int) IEventRequestUnstakeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventRequestUnstakeDo
	Unscoped() IEventRequestUnstakeDo
	Create(values ...*model.EventRequestUnstake) error
	CreateInBatches(values []*model.EventRequestUnstake, batchSize int) error
	Save(values ...*model.EventRequestUnstake) error
	First() (*model.EventRequestUnstake, error)
	Take() (*model.EventRequestUnstake, error)
	Last() (*model.EventRequestUnstake, error)
	Find() ([]*model.EventRequestUnstake, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventRequestUnstake, err error)
	FindInBatches(result *[]*model.EventRequestUnstake, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventRequestUnstake) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventRequestUnstakeDo
	Assign(attrs ...field.AssignExpr) IEventRequestUnstakeDo
	Joins(fields ...field.RelationField) IEventRequestUnstakeDo
	Preload(fields ...field.RelationField) IEventRequestUnstakeDo
	FirstOrInit() (*model.EventRequestUnstake, error)
	FirstOrCreate() (*model.EventRequestUnstake, error)
	FindByPage(offset int, limit int) (result []*model.EventRequestUnstake, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventRequestUnstakeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventRequestUnstakeDo) Debug() IEventRequestUnstakeDo {
	return e.withDO(e.DO.Debug())
}

func (e eventRequestUnstakeDo) WithContext(ctx context.Context) IEventRequestUnstakeDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventRequestUnstakeDo) ReadDB() IEventRequestUnstakeDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventRequestUnstakeDo) WriteDB() IEventRequestUnstakeDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventRequestUnstakeDo) Session(config *gorm.Session) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventRequestUnstakeDo) Clauses(conds ...clause.Expression) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventRequestUnstakeDo) Returning(value interface{}, columns ...string) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventRequestUnstakeDo) Not(conds ...gen.Condition) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventRequestUnstakeDo) Or(conds ...gen.Condition) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventRequestUnstakeDo) Select(conds ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventRequestUnstakeDo) Where(conds ...gen.Condition) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventRequestUnstakeDo) Order(conds ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventRequestUnstakeDo) Distinct(cols ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventRequestUnstakeDo) Omit(cols ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventRequestUnstakeDo) Join(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventRequestUnstakeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventRequestUnstakeDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventRequestUnstakeDo) Group(cols ...field.Expr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventRequestUnstakeDo) Having(conds ...gen.Condition) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventRequestUnstakeDo) Limit(limit int) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventRequestUnstakeDo) Offset(offset int) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventRequestUnstakeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventRequestUnstakeDo) Unscoped() IEventRequestUnstakeDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventRequestUnstakeDo) Create(values ...*model.EventRequestUnstake) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventRequestUnstakeDo) CreateInBatches(values []*model.EventRequestUnstake, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventRequestUnstakeDo) Save(values ...*model.EventRequestUnstake) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventRequestUnstakeDo) First() (*model.EventRequestUnstake, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRequestUnstake), nil
	}
}

func (e eventRequestUnstakeDo) Take() (*model.EventRequestUnstake, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRequestUnstake), nil
	}
}

func (e eventRequestUnstakeDo) Last() (*model.EventRequestUnstake, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRequestUnstake), nil
	}
}

func (e eventRequestUnstakeDo) Find() ([]*model.EventRequestUnstake, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventRequestUnstake), err
}

func (e eventRequestUnstakeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventRequestUnstake, err error) {
	buf := make([]*model.EventRequestUnstake, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventRequestUnstakeDo) FindInBatches(result *[]*model.EventRequestUnstake, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventRequestUnstakeDo) Attrs(attrs ...field.AssignExpr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventRequestUnstakeDo) Assign(attrs ...field.AssignExpr) IEventRequestUnstakeDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventRequestUnstakeDo) Joins(fields ...field.RelationField) IEventRequestUnstakeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventRequestUnstakeDo) Preload(fields ...field.RelationField) IEventRequestUnstakeDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventRequestUnstakeDo) FirstOrInit() (*model.EventRequestUnstake, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRequestUnstake), nil
	}
}

func (e eventRequestUnstakeDo) FirstOrCreate() (*model.EventRequestUnstake, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventRequestUnstake), nil
	}
}

func (e eventRequestUnstakeDo) FindByPage(offset int, limit int) (result []*model.EventRequestUnstake, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventRequestUnstakeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventRequestUnstakeDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventRequestUnstakeDo) Delete(models ...*model.EventRequestUnstake) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventRequestUnstakeDo) withDO(do gen.Dao) *eventRequestUnstakeDo {
	e.DO = *do.(*gen.DO)
	return e
}
