// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventUpdatePoolInfo(db *gorm.DB, opts ...gen.DOOption) eventUpdatePoolInfo {
	_eventUpdatePoolInfo := eventUpdatePoolInfo{}

	_eventUpdatePoolInfo.eventUpdatePoolInfoDo.UseDB(db, opts...)
	_eventUpdatePoolInfo.eventUpdatePoolInfoDo.UseModel(&model.EventUpdatePoolInfo{})

	tableName := _eventUpdatePoolInfo.eventUpdatePoolInfoDo.TableName()
	_eventUpdatePoolInfo.ALL = field.NewAsterisk(tableName)
	_eventUpdatePoolInfo.ID = field.NewInt64(tableName, "id")
	_eventUpdatePoolInfo.ContractAddress = field.NewString(tableName, "contract_address")
	_eventUpdatePoolInfo.PoolID = field.NewInt32(tableName, "pool_id")
	_eventUpdatePoolInfo.MinDepositAmount = field.NewFloat64(tableName, "min_deposit_amount")
	_eventUpdatePoolInfo.UnstakeLockedBlocks = field.NewInt32(tableName, "unstake_locked_blocks")
	_eventUpdatePoolInfo.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventUpdatePoolInfo.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventUpdatePoolInfo.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventUpdatePoolInfo.LogIndex = field.NewInt32(tableName, "log_index")
	_eventUpdatePoolInfo.CreatedAt = field.NewTime(tableName, "created_at")

	_eventUpdatePoolInfo.fillFieldMap()

	return _eventUpdatePoolInfo
}

// eventUpdatePoolInfo 更新资金池信息事件表
type eventUpdatePoolInfo struct {
	eventUpdatePoolInfoDo

	ALL                 field.Asterisk
	ID                  field.Int64
	ContractAddress     field.String
	PoolID              field.Int32   // 资金池ID
	MinDepositAmount    field.Float64 // 最小质押金额
	UnstakeLockedBlocks field.Int32   // 解锁区块数
	BlockNumber         field.Uint64
	BlockTimestamp      field.Uint64
	TransactionHash     field.String
	LogIndex            field.Int32
	CreatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (e eventUpdatePoolInfo) Table(newTableName string) *eventUpdatePoolInfo {
	e.eventUpdatePoolInfoDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventUpdatePoolInfo) As(alias string) *eventUpdatePoolInfo {
	e.eventUpdatePoolInfoDo.DO = *(e.eventUpdatePoolInfoDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventUpdatePoolInfo) updateTableName(table string) *eventUpdatePoolInfo {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.MinDepositAmount = field.NewFloat64(table, "min_deposit_amount")
	e.UnstakeLockedBlocks = field.NewInt32(table, "unstake_locked_blocks")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventUpdatePoolInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventUpdatePoolInfo) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["min_deposit_amount"] = e.MinDepositAmount
	e.fieldMap["unstake_locked_blocks"] = e.UnstakeLockedBlocks
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventUpdatePoolInfo) clone(db *gorm.DB) eventUpdatePoolInfo {
	e.eventUpdatePoolInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventUpdatePoolInfo) replaceDB(db *gorm.DB) eventUpdatePoolInfo {
	e.eventUpdatePoolInfoDo.ReplaceDB(db)
	return e
}

type eventUpdatePoolInfoDo struct{ gen.DO }

type IEventUpdatePoolInfoDo interface {
	gen.SubQuery
	Debug() IEventUpdatePoolInfoDo
	WithContext(ctx context.Context) IEventUpdatePoolInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventUpdatePoolInfoDo
	WriteDB() IEventUpdatePoolInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventUpdatePoolInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventUpdatePoolInfoDo
	Not(conds ...gen.Condition) IEventUpdatePoolInfoDo
	Or(conds ...gen.Condition) IEventUpdatePoolInfoDo
	Select(conds ...field.Expr) IEventUpdatePoolInfoDo
	Where(conds ...gen.Condition) IEventUpdatePoolInfoDo
	Order(conds ...field.Expr) IEventUpdatePoolInfoDo
	Distinct(cols ...field.Expr) IEventUpdatePoolInfoDo
	Omit(cols ...field.Expr) IEventUpdatePoolInfoDo
	Join(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo
	Group(cols ...field.Expr) IEventUpdatePoolInfoDo
	Having(conds ...gen.Condition) IEventUpdatePoolInfoDo
	Limit(limit int) IEventUpdatePoolInfoDo
	Offset(offset int) IEventUpdatePoolInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventUpdatePoolInfoDo
	Unscoped() IEventUpdatePoolInfoDo
	Create(values ...*model.EventUpdatePoolInfo) error
	CreateInBatches(values []*model.EventUpdatePoolInfo, batchSize int) error
	Save(values ...*model.EventUpdatePoolInfo) error
	First() (*model.EventUpdatePoolInfo, error)
	Take() (*model.EventUpdatePoolInfo, error)
	Last() (*model.EventUpdatePoolInfo, error)
	Find() ([]*model.EventUpdatePoolInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventUpdatePoolInfo, err error)
	FindInBatches(result *[]*model.EventUpdatePoolInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventUpdatePoolInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventUpdatePoolInfoDo
	Assign(attrs ...field.AssignExpr) IEventUpdatePoolInfoDo
	Joins(fields ...field.RelationField) IEventUpdatePoolInfoDo
	Preload(fields ...field.RelationField) IEventUpdatePoolInfoDo
	FirstOrInit() (*model.EventUpdatePoolInfo, error)
	FirstOrCreate() (*model.EventUpdatePoolInfo, error)
	FindByPage(offset int, limit int) (result []*model.EventUpdatePoolInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventUpdatePoolInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventUpdatePoolInfoDo) Debug() IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Debug())
}

func (e eventUpdatePoolInfoDo) WithContext(ctx context.Context) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventUpdatePoolInfoDo) ReadDB() IEventUpdatePoolInfoDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventUpdatePoolInfoDo) WriteDB() IEventUpdatePoolInfoDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventUpdatePoolInfoDo) Session(config *gorm.Session) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventUpdatePoolInfoDo) Clauses(conds ...clause.Expression) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventUpdatePoolInfoDo) Returning(value interface{}, columns ...string) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventUpdatePoolInfoDo) Not(conds ...gen.Condition) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventUpdatePoolInfoDo) Or(conds ...gen.Condition) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventUpdatePoolInfoDo) Select(conds ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventUpdatePoolInfoDo) Where(conds ...gen.Condition) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventUpdatePoolInfoDo) Order(conds ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventUpdatePoolInfoDo) Distinct(cols ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventUpdatePoolInfoDo) Omit(cols ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventUpdatePoolInfoDo) Join(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventUpdatePoolInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventUpdatePoolInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventUpdatePoolInfoDo) Group(cols ...field.Expr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventUpdatePoolInfoDo) Having(conds ...gen.Condition) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventUpdatePoolInfoDo) Limit(limit int) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventUpdatePoolInfoDo) Offset(offset int) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventUpdatePoolInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventUpdatePoolInfoDo) Unscoped() IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventUpdatePoolInfoDo) Create(values ...*model.EventUpdatePoolInfo) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventUpdatePoolInfoDo) CreateInBatches(values []*model.EventUpdatePoolInfo, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventUpdatePoolInfoDo) Save(values ...*model.EventUpdatePoolInfo) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventUpdatePoolInfoDo) First() (*model.EventUpdatePoolInfo, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePoolInfo), nil
	}
}

func (e eventUpdatePoolInfoDo) Take() (*model.EventUpdatePoolInfo, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePoolInfo), nil
	}
}

func (e eventUpdatePoolInfoDo) Last() (*model.EventUpdatePoolInfo, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePoolInfo), nil
	}
}

func (e eventUpdatePoolInfoDo) Find() ([]*model.EventUpdatePoolInfo, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventUpdatePoolInfo), err
}

func (e eventUpdatePoolInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventUpdatePoolInfo, err error) {
	buf := make([]*model.EventUpdatePoolInfo, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventUpdatePoolInfoDo) FindInBatches(result *[]*model.EventUpdatePoolInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventUpdatePoolInfoDo) Attrs(attrs ...field.AssignExpr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventUpdatePoolInfoDo) Assign(attrs ...field.AssignExpr) IEventUpdatePoolInfoDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventUpdatePoolInfoDo) Joins(fields ...field.RelationField) IEventUpdatePoolInfoDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventUpdatePoolInfoDo) Preload(fields ...field.RelationField) IEventUpdatePoolInfoDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventUpdatePoolInfoDo) FirstOrInit() (*model.EventUpdatePoolInfo, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePoolInfo), nil
	}
}

func (e eventUpdatePoolInfoDo) FirstOrCreate() (*model.EventUpdatePoolInfo, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePoolInfo), nil
	}
}

func (e eventUpdatePoolInfoDo) FindByPage(offset int, limit int) (result []*model.EventUpdatePoolInfo, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventUpdatePoolInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventUpdatePoolInfoDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventUpdatePoolInfoDo) Delete(models ...*model.EventUpdatePoolInfo) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventUpdatePoolInfoDo) withDO(do gen.Dao) *eventUpdatePoolInfoDo {
	e.DO = *do.(*gen.DO)
	return e
}
