// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newEventUpdatePool(db *gorm.DB, opts ...gen.DOOption) eventUpdatePool {
	_eventUpdatePool := eventUpdatePool{}

	_eventUpdatePool.eventUpdatePoolDo.UseDB(db, opts...)
	_eventUpdatePool.eventUpdatePoolDo.UseModel(&model.EventUpdatePool{})

	tableName := _eventUpdatePool.eventUpdatePoolDo.TableName()
	_eventUpdatePool.ALL = field.NewAsterisk(tableName)
	_eventUpdatePool.ID = field.NewInt64(tableName, "id")
	_eventUpdatePool.ContractAddress = field.NewString(tableName, "contract_address")
	_eventUpdatePool.PoolID = field.NewInt32(tableName, "pool_id")
	_eventUpdatePool.LastRewardBlock = field.NewUint64(tableName, "last_reward_block")
	_eventUpdatePool.TotalMetanode = field.NewFloat64(tableName, "total_metanode")
	_eventUpdatePool.BlockNumber = field.NewUint64(tableName, "block_number")
	_eventUpdatePool.BlockTimestamp = field.NewUint64(tableName, "block_timestamp")
	_eventUpdatePool.TransactionHash = field.NewString(tableName, "transaction_hash")
	_eventUpdatePool.LogIndex = field.NewInt32(tableName, "log_index")
	_eventUpdatePool.CreatedAt = field.NewTime(tableName, "created_at")

	_eventUpdatePool.fillFieldMap()

	return _eventUpdatePool
}

// eventUpdatePool 更新资金池事件表
type eventUpdatePool struct {
	eventUpdatePoolDo

	ALL             field.Asterisk
	ID              field.Int64
	ContractAddress field.String
	PoolID          field.Int32   // 资金池ID
	LastRewardBlock field.Uint64  // 最后奖励区块
	TotalMetanode   field.Float64 // 本次更新的总MetaNode奖励
	BlockNumber     field.Uint64
	BlockTimestamp  field.Uint64
	TransactionHash field.String
	LogIndex        field.Int32
	CreatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (e eventUpdatePool) Table(newTableName string) *eventUpdatePool {
	e.eventUpdatePoolDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eventUpdatePool) As(alias string) *eventUpdatePool {
	e.eventUpdatePoolDo.DO = *(e.eventUpdatePoolDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eventUpdatePool) updateTableName(table string) *eventUpdatePool {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "id")
	e.ContractAddress = field.NewString(table, "contract_address")
	e.PoolID = field.NewInt32(table, "pool_id")
	e.LastRewardBlock = field.NewUint64(table, "last_reward_block")
	e.TotalMetanode = field.NewFloat64(table, "total_metanode")
	e.BlockNumber = field.NewUint64(table, "block_number")
	e.BlockTimestamp = field.NewUint64(table, "block_timestamp")
	e.TransactionHash = field.NewString(table, "transaction_hash")
	e.LogIndex = field.NewInt32(table, "log_index")
	e.CreatedAt = field.NewTime(table, "created_at")

	e.fillFieldMap()

	return e
}

func (e *eventUpdatePool) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eventUpdatePool) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 10)
	e.fieldMap["id"] = e.ID
	e.fieldMap["contract_address"] = e.ContractAddress
	e.fieldMap["pool_id"] = e.PoolID
	e.fieldMap["last_reward_block"] = e.LastRewardBlock
	e.fieldMap["total_metanode"] = e.TotalMetanode
	e.fieldMap["block_number"] = e.BlockNumber
	e.fieldMap["block_timestamp"] = e.BlockTimestamp
	e.fieldMap["transaction_hash"] = e.TransactionHash
	e.fieldMap["log_index"] = e.LogIndex
	e.fieldMap["created_at"] = e.CreatedAt
}

func (e eventUpdatePool) clone(db *gorm.DB) eventUpdatePool {
	e.eventUpdatePoolDo.ReplaceConnPool(db.Statement.ConnPool)
	return e
}

func (e eventUpdatePool) replaceDB(db *gorm.DB) eventUpdatePool {
	e.eventUpdatePoolDo.ReplaceDB(db)
	return e
}

type eventUpdatePoolDo struct{ gen.DO }

type IEventUpdatePoolDo interface {
	gen.SubQuery
	Debug() IEventUpdatePoolDo
	WithContext(ctx context.Context) IEventUpdatePoolDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IEventUpdatePoolDo
	WriteDB() IEventUpdatePoolDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IEventUpdatePoolDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IEventUpdatePoolDo
	Not(conds ...gen.Condition) IEventUpdatePoolDo
	Or(conds ...gen.Condition) IEventUpdatePoolDo
	Select(conds ...field.Expr) IEventUpdatePoolDo
	Where(conds ...gen.Condition) IEventUpdatePoolDo
	Order(conds ...field.Expr) IEventUpdatePoolDo
	Distinct(cols ...field.Expr) IEventUpdatePoolDo
	Omit(cols ...field.Expr) IEventUpdatePoolDo
	Join(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo
	RightJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo
	Group(cols ...field.Expr) IEventUpdatePoolDo
	Having(conds ...gen.Condition) IEventUpdatePoolDo
	Limit(limit int) IEventUpdatePoolDo
	Offset(offset int) IEventUpdatePoolDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IEventUpdatePoolDo
	Unscoped() IEventUpdatePoolDo
	Create(values ...*model.EventUpdatePool) error
	CreateInBatches(values []*model.EventUpdatePool, batchSize int) error
	Save(values ...*model.EventUpdatePool) error
	First() (*model.EventUpdatePool, error)
	Take() (*model.EventUpdatePool, error)
	Last() (*model.EventUpdatePool, error)
	Find() ([]*model.EventUpdatePool, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventUpdatePool, err error)
	FindInBatches(result *[]*model.EventUpdatePool, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.EventUpdatePool) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IEventUpdatePoolDo
	Assign(attrs ...field.AssignExpr) IEventUpdatePoolDo
	Joins(fields ...field.RelationField) IEventUpdatePoolDo
	Preload(fields ...field.RelationField) IEventUpdatePoolDo
	FirstOrInit() (*model.EventUpdatePool, error)
	FirstOrCreate() (*model.EventUpdatePool, error)
	FindByPage(offset int, limit int) (result []*model.EventUpdatePool, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IEventUpdatePoolDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (e eventUpdatePoolDo) Debug() IEventUpdatePoolDo {
	return e.withDO(e.DO.Debug())
}

func (e eventUpdatePoolDo) WithContext(ctx context.Context) IEventUpdatePoolDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eventUpdatePoolDo) ReadDB() IEventUpdatePoolDo {
	return e.Clauses(dbresolver.Read)
}

func (e eventUpdatePoolDo) WriteDB() IEventUpdatePoolDo {
	return e.Clauses(dbresolver.Write)
}

func (e eventUpdatePoolDo) Session(config *gorm.Session) IEventUpdatePoolDo {
	return e.withDO(e.DO.Session(config))
}

func (e eventUpdatePoolDo) Clauses(conds ...clause.Expression) IEventUpdatePoolDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eventUpdatePoolDo) Returning(value interface{}, columns ...string) IEventUpdatePoolDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eventUpdatePoolDo) Not(conds ...gen.Condition) IEventUpdatePoolDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eventUpdatePoolDo) Or(conds ...gen.Condition) IEventUpdatePoolDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eventUpdatePoolDo) Select(conds ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eventUpdatePoolDo) Where(conds ...gen.Condition) IEventUpdatePoolDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eventUpdatePoolDo) Order(conds ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eventUpdatePoolDo) Distinct(cols ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eventUpdatePoolDo) Omit(cols ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eventUpdatePoolDo) Join(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eventUpdatePoolDo) LeftJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eventUpdatePoolDo) RightJoin(table schema.Tabler, on ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eventUpdatePoolDo) Group(cols ...field.Expr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eventUpdatePoolDo) Having(conds ...gen.Condition) IEventUpdatePoolDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eventUpdatePoolDo) Limit(limit int) IEventUpdatePoolDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eventUpdatePoolDo) Offset(offset int) IEventUpdatePoolDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eventUpdatePoolDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IEventUpdatePoolDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eventUpdatePoolDo) Unscoped() IEventUpdatePoolDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eventUpdatePoolDo) Create(values ...*model.EventUpdatePool) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eventUpdatePoolDo) CreateInBatches(values []*model.EventUpdatePool, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eventUpdatePoolDo) Save(values ...*model.EventUpdatePool) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eventUpdatePoolDo) First() (*model.EventUpdatePool, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePool), nil
	}
}

func (e eventUpdatePoolDo) Take() (*model.EventUpdatePool, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePool), nil
	}
}

func (e eventUpdatePoolDo) Last() (*model.EventUpdatePool, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePool), nil
	}
}

func (e eventUpdatePoolDo) Find() ([]*model.EventUpdatePool, error) {
	result, err := e.DO.Find()
	return result.([]*model.EventUpdatePool), err
}

func (e eventUpdatePoolDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.EventUpdatePool, err error) {
	buf := make([]*model.EventUpdatePool, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eventUpdatePoolDo) FindInBatches(result *[]*model.EventUpdatePool, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eventUpdatePoolDo) Attrs(attrs ...field.AssignExpr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eventUpdatePoolDo) Assign(attrs ...field.AssignExpr) IEventUpdatePoolDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eventUpdatePoolDo) Joins(fields ...field.RelationField) IEventUpdatePoolDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eventUpdatePoolDo) Preload(fields ...field.RelationField) IEventUpdatePoolDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eventUpdatePoolDo) FirstOrInit() (*model.EventUpdatePool, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePool), nil
	}
}

func (e eventUpdatePoolDo) FirstOrCreate() (*model.EventUpdatePool, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.EventUpdatePool), nil
	}
}

func (e eventUpdatePoolDo) FindByPage(offset int, limit int) (result []*model.EventUpdatePool, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eventUpdatePoolDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eventUpdatePoolDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eventUpdatePoolDo) Delete(models ...*model.EventUpdatePool) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eventUpdatePoolDo) withDO(do gen.Dao) *eventUpdatePoolDo {
	e.DO = *do.(*gen.DO)
	return e
}
