// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.EventSetMetanodePerBlock{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.EventSetMetanodePerBlock{}) fail: %s", err)
	}
}

func Test_eventSetMetanodePerBlockQuery(t *testing.T) {
	eventSetMetanodePerBlock := newEventSetMetanodePerBlock(_gen_test_db)
	eventSetMetanodePerBlock = *eventSetMetanodePerBlock.As(eventSetMetanodePerBlock.TableName())
	_do := eventSetMetanodePerBlock.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(eventSetMetanodePerBlock.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <event_set_metanode_per_block> fail:", err)
		return
	}

	_, ok := eventSetMetanodePerBlock.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from eventSetMetanodePerBlock success")
	}

	err = _do.Create(&model.EventSetMetanodePerBlock{})
	if err != nil {
		t.Error("create item in table <event_set_metanode_per_block> fail:", err)
	}

	err = _do.Save(&model.EventSetMetanodePerBlock{})
	if err != nil {
		t.Error("create item in table <event_set_metanode_per_block> fail:", err)
	}

	err = _do.CreateInBatches([]*model.EventSetMetanodePerBlock{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Select(eventSetMetanodePerBlock.ALL).Take()
	if err != nil {
		t.Error("Take() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <event_set_metanode_per_block> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.EventSetMetanodePerBlock{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Select(eventSetMetanodePerBlock.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Select(eventSetMetanodePerBlock.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <event_set_metanode_per_block> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.ScanByPage(&model.EventSetMetanodePerBlock{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <event_set_metanode_per_block> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <event_set_metanode_per_block> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <event_set_metanode_per_block> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <event_set_metanode_per_block> fail:", err)
	}
}
