// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newPoolInfo(db *gorm.DB, opts ...gen.DOOption) poolInfo {
	_poolInfo := poolInfo{}

	_poolInfo.poolInfoDo.UseDB(db, opts...)
	_poolInfo.poolInfoDo.UseModel(&model.PoolInfo{})

	tableName := _poolInfo.poolInfoDo.TableName()
	_poolInfo.ALL = field.NewAsterisk(tableName)
	_poolInfo.ID = field.NewInt32(tableName, "id")
	_poolInfo.PoolID = field.NewInt32(tableName, "pool_id")
	_poolInfo.ContractAddress = field.NewString(tableName, "contract_address")
	_poolInfo.StTokenAddress = field.NewString(tableName, "st_token_address")
	_poolInfo.PoolWeight = field.NewFloat64(tableName, "pool_weight")
	_poolInfo.LastRewardBlock = field.NewUint64(tableName, "last_reward_block")
	_poolInfo.AccMetanodePerSt = field.NewFloat64(tableName, "acc_metanode_per_st")
	_poolInfo.StTokenAmount = field.NewFloat64(tableName, "st_token_amount")
	_poolInfo.MinDepositAmount = field.NewFloat64(tableName, "min_deposit_amount")
	_poolInfo.UnstakeLockedBlocks = field.NewInt32(tableName, "unstake_locked_blocks")
	_poolInfo.TotalPoolWeight = field.NewFloat64(tableName, "total_pool_weight")
	_poolInfo.IsActive = field.NewBool(tableName, "is_active")
	_poolInfo.CreatedBlock = field.NewUint64(tableName, "created_block")
	_poolInfo.CreatedTx = field.NewString(tableName, "created_tx")
	_poolInfo.CreatedAt = field.NewTime(tableName, "created_at")
	_poolInfo.UpdatedAt = field.NewTime(tableName, "updated_at")

	_poolInfo.fillFieldMap()

	return _poolInfo
}

// poolInfo 资金池信息表
type poolInfo struct {
	poolInfoDo

	ALL                 field.Asterisk
	ID                  field.Int32
	PoolID              field.Int32   // 资金池ID
	ContractAddress     field.String  // 合约地址
	StTokenAddress      field.String  // 质押代币地址 (0x0 表示ETH)
	PoolWeight          field.Float64 // 资金池权重
	LastRewardBlock     field.Uint64  // 最后奖励区块
	AccMetanodePerSt    field.Float64 // 每质押代币累计MetaNode
	StTokenAmount       field.Float64 // 质押代币总量
	MinDepositAmount    field.Float64 // 最小质押金额
	UnstakeLockedBlocks field.Int32   // 解锁区块数
	TotalPoolWeight     field.Float64 // 所有池的总权重
	IsActive            field.Bool    // 是否激活
	CreatedBlock        field.Uint64  // 创建时的区块号
	CreatedTx           field.String  // 创建交易哈希
	CreatedAt           field.Time
	UpdatedAt           field.Time

	fieldMap map[string]field.Expr
}

func (p poolInfo) Table(newTableName string) *poolInfo {
	p.poolInfoDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p poolInfo) As(alias string) *poolInfo {
	p.poolInfoDo.DO = *(p.poolInfoDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *poolInfo) updateTableName(table string) *poolInfo {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt32(table, "id")
	p.PoolID = field.NewInt32(table, "pool_id")
	p.ContractAddress = field.NewString(table, "contract_address")
	p.StTokenAddress = field.NewString(table, "st_token_address")
	p.PoolWeight = field.NewFloat64(table, "pool_weight")
	p.LastRewardBlock = field.NewUint64(table, "last_reward_block")
	p.AccMetanodePerSt = field.NewFloat64(table, "acc_metanode_per_st")
	p.StTokenAmount = field.NewFloat64(table, "st_token_amount")
	p.MinDepositAmount = field.NewFloat64(table, "min_deposit_amount")
	p.UnstakeLockedBlocks = field.NewInt32(table, "unstake_locked_blocks")
	p.TotalPoolWeight = field.NewFloat64(table, "total_pool_weight")
	p.IsActive = field.NewBool(table, "is_active")
	p.CreatedBlock = field.NewUint64(table, "created_block")
	p.CreatedTx = field.NewString(table, "created_tx")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")

	p.fillFieldMap()

	return p
}

func (p *poolInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *poolInfo) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 16)
	p.fieldMap["id"] = p.ID
	p.fieldMap["pool_id"] = p.PoolID
	p.fieldMap["contract_address"] = p.ContractAddress
	p.fieldMap["st_token_address"] = p.StTokenAddress
	p.fieldMap["pool_weight"] = p.PoolWeight
	p.fieldMap["last_reward_block"] = p.LastRewardBlock
	p.fieldMap["acc_metanode_per_st"] = p.AccMetanodePerSt
	p.fieldMap["st_token_amount"] = p.StTokenAmount
	p.fieldMap["min_deposit_amount"] = p.MinDepositAmount
	p.fieldMap["unstake_locked_blocks"] = p.UnstakeLockedBlocks
	p.fieldMap["total_pool_weight"] = p.TotalPoolWeight
	p.fieldMap["is_active"] = p.IsActive
	p.fieldMap["created_block"] = p.CreatedBlock
	p.fieldMap["created_tx"] = p.CreatedTx
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
}

func (p poolInfo) clone(db *gorm.DB) poolInfo {
	p.poolInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p poolInfo) replaceDB(db *gorm.DB) poolInfo {
	p.poolInfoDo.ReplaceDB(db)
	return p
}

type poolInfoDo struct{ gen.DO }

type IPoolInfoDo interface {
	gen.SubQuery
	Debug() IPoolInfoDo
	WithContext(ctx context.Context) IPoolInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPoolInfoDo
	WriteDB() IPoolInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPoolInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPoolInfoDo
	Not(conds ...gen.Condition) IPoolInfoDo
	Or(conds ...gen.Condition) IPoolInfoDo
	Select(conds ...field.Expr) IPoolInfoDo
	Where(conds ...gen.Condition) IPoolInfoDo
	Order(conds ...field.Expr) IPoolInfoDo
	Distinct(cols ...field.Expr) IPoolInfoDo
	Omit(cols ...field.Expr) IPoolInfoDo
	Join(table schema.Tabler, on ...field.Expr) IPoolInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPoolInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPoolInfoDo
	Group(cols ...field.Expr) IPoolInfoDo
	Having(conds ...gen.Condition) IPoolInfoDo
	Limit(limit int) IPoolInfoDo
	Offset(offset int) IPoolInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolInfoDo
	Unscoped() IPoolInfoDo
	Create(values ...*model.PoolInfo) error
	CreateInBatches(values []*model.PoolInfo, batchSize int) error
	Save(values ...*model.PoolInfo) error
	First() (*model.PoolInfo, error)
	Take() (*model.PoolInfo, error)
	Last() (*model.PoolInfo, error)
	Find() ([]*model.PoolInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PoolInfo, err error)
	FindInBatches(result *[]*model.PoolInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PoolInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPoolInfoDo
	Assign(attrs ...field.AssignExpr) IPoolInfoDo
	Joins(fields ...field.RelationField) IPoolInfoDo
	Preload(fields ...field.RelationField) IPoolInfoDo
	FirstOrInit() (*model.PoolInfo, error)
	FirstOrCreate() (*model.PoolInfo, error)
	FindByPage(offset int, limit int) (result []*model.PoolInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPoolInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p poolInfoDo) Debug() IPoolInfoDo {
	return p.withDO(p.DO.Debug())
}

func (p poolInfoDo) WithContext(ctx context.Context) IPoolInfoDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p poolInfoDo) ReadDB() IPoolInfoDo {
	return p.Clauses(dbresolver.Read)
}

func (p poolInfoDo) WriteDB() IPoolInfoDo {
	return p.Clauses(dbresolver.Write)
}

func (p poolInfoDo) Session(config *gorm.Session) IPoolInfoDo {
	return p.withDO(p.DO.Session(config))
}

func (p poolInfoDo) Clauses(conds ...clause.Expression) IPoolInfoDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p poolInfoDo) Returning(value interface{}, columns ...string) IPoolInfoDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p poolInfoDo) Not(conds ...gen.Condition) IPoolInfoDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p poolInfoDo) Or(conds ...gen.Condition) IPoolInfoDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p poolInfoDo) Select(conds ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p poolInfoDo) Where(conds ...gen.Condition) IPoolInfoDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p poolInfoDo) Order(conds ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p poolInfoDo) Distinct(cols ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p poolInfoDo) Omit(cols ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p poolInfoDo) Join(table schema.Tabler, on ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p poolInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p poolInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p poolInfoDo) Group(cols ...field.Expr) IPoolInfoDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p poolInfoDo) Having(conds ...gen.Condition) IPoolInfoDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p poolInfoDo) Limit(limit int) IPoolInfoDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p poolInfoDo) Offset(offset int) IPoolInfoDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p poolInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPoolInfoDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p poolInfoDo) Unscoped() IPoolInfoDo {
	return p.withDO(p.DO.Unscoped())
}

func (p poolInfoDo) Create(values ...*model.PoolInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p poolInfoDo) CreateInBatches(values []*model.PoolInfo, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p poolInfoDo) Save(values ...*model.PoolInfo) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p poolInfoDo) First() (*model.PoolInfo, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PoolInfo), nil
	}
}

func (p poolInfoDo) Take() (*model.PoolInfo, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PoolInfo), nil
	}
}

func (p poolInfoDo) Last() (*model.PoolInfo, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PoolInfo), nil
	}
}

func (p poolInfoDo) Find() ([]*model.PoolInfo, error) {
	result, err := p.DO.Find()
	return result.([]*model.PoolInfo), err
}

func (p poolInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PoolInfo, err error) {
	buf := make([]*model.PoolInfo, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p poolInfoDo) FindInBatches(result *[]*model.PoolInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p poolInfoDo) Attrs(attrs ...field.AssignExpr) IPoolInfoDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p poolInfoDo) Assign(attrs ...field.AssignExpr) IPoolInfoDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p poolInfoDo) Joins(fields ...field.RelationField) IPoolInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p poolInfoDo) Preload(fields ...field.RelationField) IPoolInfoDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p poolInfoDo) FirstOrInit() (*model.PoolInfo, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PoolInfo), nil
	}
}

func (p poolInfoDo) FirstOrCreate() (*model.PoolInfo, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PoolInfo), nil
	}
}

func (p poolInfoDo) FindByPage(offset int, limit int) (result []*model.PoolInfo, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p poolInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p poolInfoDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p poolInfoDo) Delete(models ...*model.PoolInfo) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *poolInfoDo) withDO(do gen.Dao) *poolInfoDo {
	p.DO = *do.(*gen.DO)
	return p
}
