// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newSyncStatus(db *gorm.DB, opts ...gen.DOOption) syncStatus {
	_syncStatus := syncStatus{}

	_syncStatus.syncStatusDo.UseDB(db, opts...)
	_syncStatus.syncStatusDo.UseModel(&model.SyncStatus{})

	tableName := _syncStatus.syncStatusDo.TableName()
	_syncStatus.ALL = field.NewAsterisk(tableName)
	_syncStatus.ID = field.NewInt32(tableName, "id")
	_syncStatus.ContractAddress = field.NewString(tableName, "contract_address")
	_syncStatus.ChainID = field.NewInt32(tableName, "chain_id")
	_syncStatus.LastSyncedBlock = field.NewUint64(tableName, "last_synced_block")
	_syncStatus.LastSyncTime = field.NewTime(tableName, "last_sync_time")
	_syncStatus.SyncError = field.NewString(tableName, "sync_error")
	_syncStatus.IsSyncing = field.NewBool(tableName, "is_syncing")
	_syncStatus.CreatedAt = field.NewTime(tableName, "created_at")
	_syncStatus.UpdatedAt = field.NewTime(tableName, "updated_at")

	_syncStatus.fillFieldMap()

	return _syncStatus
}

// syncStatus 区块链同步状态表
type syncStatus struct {
	syncStatusDo

	ALL             field.Asterisk
	ID              field.Int32
	ContractAddress field.String // 合约地址
	ChainID         field.Int32  // 链ID (如 11155111 for Sepolia)
	LastSyncedBlock field.Uint64 // 最后同步的区块号
	LastSyncTime    field.Time   // 最后同步时间
	SyncError       field.String // 同步错误信息
	IsSyncing       field.Bool   // 是否正在同步
	CreatedAt       field.Time
	UpdatedAt       field.Time

	fieldMap map[string]field.Expr
}

func (s syncStatus) Table(newTableName string) *syncStatus {
	s.syncStatusDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncStatus) As(alias string) *syncStatus {
	s.syncStatusDo.DO = *(s.syncStatusDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncStatus) updateTableName(table string) *syncStatus {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.ContractAddress = field.NewString(table, "contract_address")
	s.ChainID = field.NewInt32(table, "chain_id")
	s.LastSyncedBlock = field.NewUint64(table, "last_synced_block")
	s.LastSyncTime = field.NewTime(table, "last_sync_time")
	s.SyncError = field.NewString(table, "sync_error")
	s.IsSyncing = field.NewBool(table, "is_syncing")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *syncStatus) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncStatus) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["contract_address"] = s.ContractAddress
	s.fieldMap["chain_id"] = s.ChainID
	s.fieldMap["last_synced_block"] = s.LastSyncedBlock
	s.fieldMap["last_sync_time"] = s.LastSyncTime
	s.fieldMap["sync_error"] = s.SyncError
	s.fieldMap["is_syncing"] = s.IsSyncing
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s syncStatus) clone(db *gorm.DB) syncStatus {
	s.syncStatusDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncStatus) replaceDB(db *gorm.DB) syncStatus {
	s.syncStatusDo.ReplaceDB(db)
	return s
}

type syncStatusDo struct{ gen.DO }

type ISyncStatusDo interface {
	gen.SubQuery
	Debug() ISyncStatusDo
	WithContext(ctx context.Context) ISyncStatusDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISyncStatusDo
	WriteDB() ISyncStatusDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISyncStatusDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISyncStatusDo
	Not(conds ...gen.Condition) ISyncStatusDo
	Or(conds ...gen.Condition) ISyncStatusDo
	Select(conds ...field.Expr) ISyncStatusDo
	Where(conds ...gen.Condition) ISyncStatusDo
	Order(conds ...field.Expr) ISyncStatusDo
	Distinct(cols ...field.Expr) ISyncStatusDo
	Omit(cols ...field.Expr) ISyncStatusDo
	Join(table schema.Tabler, on ...field.Expr) ISyncStatusDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISyncStatusDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISyncStatusDo
	Group(cols ...field.Expr) ISyncStatusDo
	Having(conds ...gen.Condition) ISyncStatusDo
	Limit(limit int) ISyncStatusDo
	Offset(offset int) ISyncStatusDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncStatusDo
	Unscoped() ISyncStatusDo
	Create(values ...*model.SyncStatus) error
	CreateInBatches(values []*model.SyncStatus, batchSize int) error
	Save(values ...*model.SyncStatus) error
	First() (*model.SyncStatus, error)
	Take() (*model.SyncStatus, error)
	Last() (*model.SyncStatus, error)
	Find() ([]*model.SyncStatus, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SyncStatus, err error)
	FindInBatches(result *[]*model.SyncStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SyncStatus) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISyncStatusDo
	Assign(attrs ...field.AssignExpr) ISyncStatusDo
	Joins(fields ...field.RelationField) ISyncStatusDo
	Preload(fields ...field.RelationField) ISyncStatusDo
	FirstOrInit() (*model.SyncStatus, error)
	FirstOrCreate() (*model.SyncStatus, error)
	FindByPage(offset int, limit int) (result []*model.SyncStatus, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISyncStatusDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s syncStatusDo) Debug() ISyncStatusDo {
	return s.withDO(s.DO.Debug())
}

func (s syncStatusDo) WithContext(ctx context.Context) ISyncStatusDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncStatusDo) ReadDB() ISyncStatusDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncStatusDo) WriteDB() ISyncStatusDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncStatusDo) Session(config *gorm.Session) ISyncStatusDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncStatusDo) Clauses(conds ...clause.Expression) ISyncStatusDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncStatusDo) Returning(value interface{}, columns ...string) ISyncStatusDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncStatusDo) Not(conds ...gen.Condition) ISyncStatusDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncStatusDo) Or(conds ...gen.Condition) ISyncStatusDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncStatusDo) Select(conds ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncStatusDo) Where(conds ...gen.Condition) ISyncStatusDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncStatusDo) Order(conds ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncStatusDo) Distinct(cols ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncStatusDo) Omit(cols ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncStatusDo) Join(table schema.Tabler, on ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncStatusDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncStatusDo) RightJoin(table schema.Tabler, on ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncStatusDo) Group(cols ...field.Expr) ISyncStatusDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncStatusDo) Having(conds ...gen.Condition) ISyncStatusDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncStatusDo) Limit(limit int) ISyncStatusDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncStatusDo) Offset(offset int) ISyncStatusDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncStatusDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISyncStatusDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncStatusDo) Unscoped() ISyncStatusDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncStatusDo) Create(values ...*model.SyncStatus) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncStatusDo) CreateInBatches(values []*model.SyncStatus, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncStatusDo) Save(values ...*model.SyncStatus) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncStatusDo) First() (*model.SyncStatus, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncStatus), nil
	}
}

func (s syncStatusDo) Take() (*model.SyncStatus, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncStatus), nil
	}
}

func (s syncStatusDo) Last() (*model.SyncStatus, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncStatus), nil
	}
}

func (s syncStatusDo) Find() ([]*model.SyncStatus, error) {
	result, err := s.DO.Find()
	return result.([]*model.SyncStatus), err
}

func (s syncStatusDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SyncStatus, err error) {
	buf := make([]*model.SyncStatus, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncStatusDo) FindInBatches(result *[]*model.SyncStatus, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncStatusDo) Attrs(attrs ...field.AssignExpr) ISyncStatusDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncStatusDo) Assign(attrs ...field.AssignExpr) ISyncStatusDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncStatusDo) Joins(fields ...field.RelationField) ISyncStatusDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncStatusDo) Preload(fields ...field.RelationField) ISyncStatusDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncStatusDo) FirstOrInit() (*model.SyncStatus, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncStatus), nil
	}
}

func (s syncStatusDo) FirstOrCreate() (*model.SyncStatus, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncStatus), nil
	}
}

func (s syncStatusDo) FindByPage(offset int, limit int) (result []*model.SyncStatus, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncStatusDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncStatusDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncStatusDo) Delete(models ...*model.SyncStatus) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncStatusDo) withDO(do gen.Dao) *syncStatusDo {
	s.DO = *do.(*gen.DO)
	return s
}
