// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/dijiacoder/MetaNodeStakeSync/dao/model"
)

func newUserPoolStat(db *gorm.DB, opts ...gen.DOOption) userPoolStat {
	_userPoolStat := userPoolStat{}

	_userPoolStat.userPoolStatDo.UseDB(db, opts...)
	_userPoolStat.userPoolStatDo.UseModel(&model.UserPoolStat{})

	tableName := _userPoolStat.userPoolStatDo.TableName()
	_userPoolStat.ALL = field.NewAsterisk(tableName)
	_userPoolStat.ID = field.NewInt64(tableName, "id")
	_userPoolStat.UserAddress = field.NewString(tableName, "user_address")
	_userPoolStat.PoolID = field.NewInt32(tableName, "pool_id")
	_userPoolStat.ContractAddress = field.NewString(tableName, "contract_address")
	_userPoolStat.StAmount = field.NewFloat64(tableName, "st_amount")
	_userPoolStat.FinishedMetanode = field.NewFloat64(tableName, "finished_metanode")
	_userPoolStat.PendingMetanode = field.NewFloat64(tableName, "pending_metanode")
	_userPoolStat.TotalDeposited = field.NewFloat64(tableName, "total_deposited")
	_userPoolStat.TotalUnstaked = field.NewFloat64(tableName, "total_unstaked")
	_userPoolStat.TotalWithdrawn = field.NewFloat64(tableName, "total_withdrawn")
	_userPoolStat.TotalClaimed = field.NewFloat64(tableName, "total_claimed")
	_userPoolStat.LastDepositBlock = field.NewUint64(tableName, "last_deposit_block")
	_userPoolStat.LastClaimBlock = field.NewUint64(tableName, "last_claim_block")
	_userPoolStat.CreatedAt = field.NewTime(tableName, "created_at")
	_userPoolStat.UpdatedAt = field.NewTime(tableName, "updated_at")

	_userPoolStat.fillFieldMap()

	return _userPoolStat
}

// userPoolStat 用户资金池统计表
type userPoolStat struct {
	userPoolStatDo

	ALL              field.Asterisk
	ID               field.Int64
	UserAddress      field.String  // 用户地址
	PoolID           field.Int32   // 资金池ID
	ContractAddress  field.String  // 合约地址
	StAmount         field.Float64 // 当前质押金额
	FinishedMetanode field.Float64 // 已领取的MetaNode
	PendingMetanode  field.Float64 // 待领取的MetaNode
	TotalDeposited   field.Float64 // 累计质押金额
	TotalUnstaked    field.Float64 // 累计解质押金额
	TotalWithdrawn   field.Float64 // 累计提现金额
	TotalClaimed     field.Float64 // 累计领取奖励
	LastDepositBlock field.Uint64  // 最后质押区块
	LastClaimBlock   field.Uint64  // 最后领取区块
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (u userPoolStat) Table(newTableName string) *userPoolStat {
	u.userPoolStatDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userPoolStat) As(alias string) *userPoolStat {
	u.userPoolStatDo.DO = *(u.userPoolStatDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userPoolStat) updateTableName(table string) *userPoolStat {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewInt64(table, "id")
	u.UserAddress = field.NewString(table, "user_address")
	u.PoolID = field.NewInt32(table, "pool_id")
	u.ContractAddress = field.NewString(table, "contract_address")
	u.StAmount = field.NewFloat64(table, "st_amount")
	u.FinishedMetanode = field.NewFloat64(table, "finished_metanode")
	u.PendingMetanode = field.NewFloat64(table, "pending_metanode")
	u.TotalDeposited = field.NewFloat64(table, "total_deposited")
	u.TotalUnstaked = field.NewFloat64(table, "total_unstaked")
	u.TotalWithdrawn = field.NewFloat64(table, "total_withdrawn")
	u.TotalClaimed = field.NewFloat64(table, "total_claimed")
	u.LastDepositBlock = field.NewUint64(table, "last_deposit_block")
	u.LastClaimBlock = field.NewUint64(table, "last_claim_block")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UpdatedAt = field.NewTime(table, "updated_at")

	u.fillFieldMap()

	return u
}

func (u *userPoolStat) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userPoolStat) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 15)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_address"] = u.UserAddress
	u.fieldMap["pool_id"] = u.PoolID
	u.fieldMap["contract_address"] = u.ContractAddress
	u.fieldMap["st_amount"] = u.StAmount
	u.fieldMap["finished_metanode"] = u.FinishedMetanode
	u.fieldMap["pending_metanode"] = u.PendingMetanode
	u.fieldMap["total_deposited"] = u.TotalDeposited
	u.fieldMap["total_unstaked"] = u.TotalUnstaked
	u.fieldMap["total_withdrawn"] = u.TotalWithdrawn
	u.fieldMap["total_claimed"] = u.TotalClaimed
	u.fieldMap["last_deposit_block"] = u.LastDepositBlock
	u.fieldMap["last_claim_block"] = u.LastClaimBlock
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
}

func (u userPoolStat) clone(db *gorm.DB) userPoolStat {
	u.userPoolStatDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userPoolStat) replaceDB(db *gorm.DB) userPoolStat {
	u.userPoolStatDo.ReplaceDB(db)
	return u
}

type userPoolStatDo struct{ gen.DO }

type IUserPoolStatDo interface {
	gen.SubQuery
	Debug() IUserPoolStatDo
	WithContext(ctx context.Context) IUserPoolStatDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserPoolStatDo
	WriteDB() IUserPoolStatDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserPoolStatDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserPoolStatDo
	Not(conds ...gen.Condition) IUserPoolStatDo
	Or(conds ...gen.Condition) IUserPoolStatDo
	Select(conds ...field.Expr) IUserPoolStatDo
	Where(conds ...gen.Condition) IUserPoolStatDo
	Order(conds ...field.Expr) IUserPoolStatDo
	Distinct(cols ...field.Expr) IUserPoolStatDo
	Omit(cols ...field.Expr) IUserPoolStatDo
	Join(table schema.Tabler, on ...field.Expr) IUserPoolStatDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserPoolStatDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserPoolStatDo
	Group(cols ...field.Expr) IUserPoolStatDo
	Having(conds ...gen.Condition) IUserPoolStatDo
	Limit(limit int) IUserPoolStatDo
	Offset(offset int) IUserPoolStatDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPoolStatDo
	Unscoped() IUserPoolStatDo
	Create(values ...*model.UserPoolStat) error
	CreateInBatches(values []*model.UserPoolStat, batchSize int) error
	Save(values ...*model.UserPoolStat) error
	First() (*model.UserPoolStat, error)
	Take() (*model.UserPoolStat, error)
	Last() (*model.UserPoolStat, error)
	Find() ([]*model.UserPoolStat, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserPoolStat, err error)
	FindInBatches(result *[]*model.UserPoolStat, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserPoolStat) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserPoolStatDo
	Assign(attrs ...field.AssignExpr) IUserPoolStatDo
	Joins(fields ...field.RelationField) IUserPoolStatDo
	Preload(fields ...field.RelationField) IUserPoolStatDo
	FirstOrInit() (*model.UserPoolStat, error)
	FirstOrCreate() (*model.UserPoolStat, error)
	FindByPage(offset int, limit int) (result []*model.UserPoolStat, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserPoolStatDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userPoolStatDo) Debug() IUserPoolStatDo {
	return u.withDO(u.DO.Debug())
}

func (u userPoolStatDo) WithContext(ctx context.Context) IUserPoolStatDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userPoolStatDo) ReadDB() IUserPoolStatDo {
	return u.Clauses(dbresolver.Read)
}

func (u userPoolStatDo) WriteDB() IUserPoolStatDo {
	return u.Clauses(dbresolver.Write)
}

func (u userPoolStatDo) Session(config *gorm.Session) IUserPoolStatDo {
	return u.withDO(u.DO.Session(config))
}

func (u userPoolStatDo) Clauses(conds ...clause.Expression) IUserPoolStatDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userPoolStatDo) Returning(value interface{}, columns ...string) IUserPoolStatDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userPoolStatDo) Not(conds ...gen.Condition) IUserPoolStatDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userPoolStatDo) Or(conds ...gen.Condition) IUserPoolStatDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userPoolStatDo) Select(conds ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userPoolStatDo) Where(conds ...gen.Condition) IUserPoolStatDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userPoolStatDo) Order(conds ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userPoolStatDo) Distinct(cols ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userPoolStatDo) Omit(cols ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userPoolStatDo) Join(table schema.Tabler, on ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userPoolStatDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userPoolStatDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userPoolStatDo) Group(cols ...field.Expr) IUserPoolStatDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userPoolStatDo) Having(conds ...gen.Condition) IUserPoolStatDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userPoolStatDo) Limit(limit int) IUserPoolStatDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userPoolStatDo) Offset(offset int) IUserPoolStatDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userPoolStatDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserPoolStatDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userPoolStatDo) Unscoped() IUserPoolStatDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userPoolStatDo) Create(values ...*model.UserPoolStat) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userPoolStatDo) CreateInBatches(values []*model.UserPoolStat, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userPoolStatDo) Save(values ...*model.UserPoolStat) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userPoolStatDo) First() (*model.UserPoolStat, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPoolStat), nil
	}
}

func (u userPoolStatDo) Take() (*model.UserPoolStat, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPoolStat), nil
	}
}

func (u userPoolStatDo) Last() (*model.UserPoolStat, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPoolStat), nil
	}
}

func (u userPoolStatDo) Find() ([]*model.UserPoolStat, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserPoolStat), err
}

func (u userPoolStatDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserPoolStat, err error) {
	buf := make([]*model.UserPoolStat, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userPoolStatDo) FindInBatches(result *[]*model.UserPoolStat, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userPoolStatDo) Attrs(attrs ...field.AssignExpr) IUserPoolStatDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userPoolStatDo) Assign(attrs ...field.AssignExpr) IUserPoolStatDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userPoolStatDo) Joins(fields ...field.RelationField) IUserPoolStatDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userPoolStatDo) Preload(fields ...field.RelationField) IUserPoolStatDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userPoolStatDo) FirstOrInit() (*model.UserPoolStat, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPoolStat), nil
	}
}

func (u userPoolStatDo) FirstOrCreate() (*model.UserPoolStat, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserPoolStat), nil
	}
}

func (u userPoolStatDo) FindByPage(offset int, limit int) (result []*model.UserPoolStat, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userPoolStatDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userPoolStatDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userPoolStatDo) Delete(models ...*model.UserPoolStat) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userPoolStatDo) withDO(do gen.Dao) *userPoolStatDo {
	u.DO = *do.(*gen.DO)
	return u
}
