// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainContract = "chain_contracts"

// ChainContract 链合约信息表
type ChainContract struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ChainID         int32      `gorm:"column:chain_id;type:int;not null;index:idx_chain_id,priority:1;comment:链ID (如 1 for Ethereum Mainnet, 11155111 for Sepolia)" json:"chain_id"` // 链ID (如 1 for Ethereum Mainnet, 11155111 for Sepolia)
	ContractName    int32      `gorm:"column:contract_name;type:int;not null;index:idx_contract_name,priority:1;comment:合约名称标识符" json:"contract_name"`                               // 合约名称标识符
	ContractAddress string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract_address,priority:1;comment:合约地址" json:"contract_address"`                 // 合约地址
	CreatedTxHash   *string    `gorm:"column:created_tx_hash;type:varchar(66);comment:创建交易哈希" json:"created_tx_hash"`                                                                // 创建交易哈希
	Abi             string     `gorm:"column:abi;type:text;not null;comment:合约ABI" json:"abi"`                                                                                       // 合约ABI
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ChainContract's table name
func (*ChainContract) TableName() string {
	return TableNameChainContract
}
