// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChainEndpoint = "chain_endpoints"

// ChainEndpoint 链端点信息表
type ChainEndpoint struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ChainID   int32      `gorm:"column:chain_id;type:int;not null;uniqueIndex:chain_id,priority:1;uniqueIndex:uk_chain_id,priority:1;comment:链ID" json:"chain_id"` // 链ID
	URL       string     `gorm:"column:url;type:varchar(255);not null;comment:RPC端点URL" json:"url"`                                                                // RPC端点URL
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ChainEndpoint's table name
func (*ChainEndpoint) TableName() string {
	return TableNameChainEndpoint
}
