// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameContractEvent = "contract_events"

// ContractEvent Contract events table (unified)
type ContractEvent struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress string     `gorm:"column:contract_address;type:varchar(255);not null;index:idx_contract,priority:1;index:idx_contract_event,priority:1;comment:Contract address" json:"contract_address"`                  // Contract address
	EventName       string     `gorm:"column:event_name;type:varchar(100);not null;index:idx_block_event,priority:2;index:idx_contract_event,priority:2;index:idx_event_name,priority:1;comment:Event name" json:"event_name"` // Event name
	Topic0          string     `gorm:"column:topic0;type:varchar(255);not null;index:idx_topic0,priority:1;comment:Event signature hash" json:"topic0"`                                                                        // Event signature hash
	Topic1          *string    `gorm:"column:topic1;type:varchar(255);comment:Indexed parameter 1" json:"topic1"`                                                                                                              // Indexed parameter 1
	Topic2          *string    `gorm:"column:topic2;type:varchar(255);comment:Indexed parameter 2" json:"topic2"`                                                                                                              // Indexed parameter 2
	Topic3          *string    `gorm:"column:topic3;type:varchar(255);comment:Indexed parameter 3" json:"topic3"`                                                                                                              // Indexed parameter 3
	Data            *string    `gorm:"column:data;type:text;comment:Event data (hex string)" json:"data"`                                                                                                                      // Event data (hex string)
	BlockNumber     uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1;index:idx_block_event,priority:1;comment:Block number" json:"block_number"`                                 // Block number
	BlockTimestamp  uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null;comment:Block timestamp" json:"block_timestamp"`                                                                                    // Block timestamp
	TransactionHash string     `gorm:"column:transaction_hash;type:varchar(255);not null;uniqueIndex:uk_tx_log,priority:1;comment:Transaction hash" json:"transaction_hash"`                                                   // Transaction hash
	LogIndex        int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2;comment:Log index in transaction" json:"log_index"`                                                                  // Log index in transaction
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName ContractEvent's table name
func (*ContractEvent) TableName() string {
	return TableNameContractEvent
}
