// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventUpdatePoolInfo = "event_update_pool_info"

// EventUpdatePoolInfo 更新资金池信息事件表
type EventUpdatePoolInfo struct {
	ID                  int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress     string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract,priority:1" json:"contract_address"`
	PoolID              int32      `gorm:"column:pool_id;type:int;not null;index:idx_pool,priority:1;comment:资金池ID" json:"pool_id"`         // 资金池ID
	MinDepositAmount    float64    `gorm:"column:min_deposit_amount;type:decimal(65,18);not null;comment:最小质押金额" json:"min_deposit_amount"` // 最小质押金额
	UnstakeLockedBlocks int32      `gorm:"column:unstake_locked_blocks;type:int;not null;comment:解锁区块数" json:"unstake_locked_blocks"`       // 解锁区块数
	BlockNumber         uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1" json:"block_number"`
	BlockTimestamp      uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null" json:"block_timestamp"`
	TransactionHash     string     `gorm:"column:transaction_hash;type:varchar(66);not null;uniqueIndex:uk_tx_log,priority:1" json:"transaction_hash"`
	LogIndex            int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2" json:"log_index"`
	CreatedAt           *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventUpdatePoolInfo's table name
func (*EventUpdatePoolInfo) TableName() string {
	return TableNameEventUpdatePoolInfo
}
