// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventDeposit = "event_deposit"

// EventDeposit 质押事件表
type EventDeposit struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract,priority:1" json:"contract_address"`
	UserAddress     string     `gorm:"column:user_address;type:varchar(42);not null;index:idx_user,priority:1;index:idx_user_pool,priority:1;comment:用户地址" json:"user_address"` // 用户地址
	PoolID          int32      `gorm:"column:pool_id;type:int;not null;index:idx_pool,priority:1;index:idx_user_pool,priority:2;comment:资金池ID" json:"pool_id"`                  // 资金池ID
	Amount          float64    `gorm:"column:amount;type:decimal(65,18);not null;comment:质押金额" json:"amount"`                                                                   // 质押金额
	BlockNumber     uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1" json:"block_number"`
	BlockTimestamp  uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null" json:"block_timestamp"`
	TransactionHash string     `gorm:"column:transaction_hash;type:varchar(66);not null;uniqueIndex:uk_tx_log,priority:1" json:"transaction_hash"`
	LogIndex        int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2" json:"log_index"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventDeposit's table name
func (*EventDeposit) TableName() string {
	return TableNameEventDeposit
}
