// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventSetPoolWeight = "event_set_pool_weight"

// EventSetPoolWeight 设置资金池权重事件表
type EventSetPoolWeight struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract,priority:1" json:"contract_address"`
	PoolID          int32      `gorm:"column:pool_id;type:int;not null;index:idx_pool,priority:1;comment:资金池ID" json:"pool_id"`       // 资金池ID
	PoolWeight      float64    `gorm:"column:pool_weight;type:decimal(30,0);not null;comment:新的资金池权重" json:"pool_weight"`             // 新的资金池权重
	TotalPoolWeight float64    `gorm:"column:total_pool_weight;type:decimal(30,0);not null;comment:所有池的总权重" json:"total_pool_weight"` // 所有池的总权重
	BlockNumber     uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1" json:"block_number"`
	BlockTimestamp  uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null" json:"block_timestamp"`
	TransactionHash string     `gorm:"column:transaction_hash;type:varchar(66);not null;uniqueIndex:uk_tx_log,priority:1" json:"transaction_hash"`
	LogIndex        int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2" json:"log_index"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventSetPoolWeight's table name
func (*EventSetPoolWeight) TableName() string {
	return TableNameEventSetPoolWeight
}
