// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventUpdatePool = "event_update_pool"

// EventUpdatePool 更新资金池事件表
type EventUpdatePool struct {
	ID              int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract,priority:1" json:"contract_address"`
	PoolID          int32      `gorm:"column:pool_id;type:int;not null;index:idx_pool,priority:1;comment:资金池ID" json:"pool_id"`           // 资金池ID
	LastRewardBlock uint64     `gorm:"column:last_reward_block;type:bigint unsigned;not null;comment:最后奖励区块" json:"last_reward_block"`    // 最后奖励区块
	TotalMetanode   float64    `gorm:"column:total_metanode;type:decimal(65,18);not null;comment:本次更新的总MetaNode奖励" json:"total_metanode"` // 本次更新的总MetaNode奖励
	BlockNumber     uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1" json:"block_number"`
	BlockTimestamp  uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null" json:"block_timestamp"`
	TransactionHash string     `gorm:"column:transaction_hash;type:varchar(66);not null;uniqueIndex:uk_tx_log,priority:1" json:"transaction_hash"`
	LogIndex        int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2" json:"log_index"`
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventUpdatePool's table name
func (*EventUpdatePool) TableName() string {
	return TableNameEventUpdatePool
}
