// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEventSetMetanodePerBlock = "event_set_metanode_per_block"

// EventSetMetanodePerBlock 设置每区块奖励事件表
type EventSetMetanodePerBlock struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress  string     `gorm:"column:contract_address;type:varchar(42);not null;index:idx_contract,priority:1" json:"contract_address"`
	MetanodePerBlock float64    `gorm:"column:metanode_per_block;type:decimal(65,18);not null;comment:每区块MetaNode奖励" json:"metanode_per_block"` // 每区块MetaNode奖励
	BlockNumber      uint64     `gorm:"column:block_number;type:bigint unsigned;not null;index:idx_block,priority:1" json:"block_number"`
	BlockTimestamp   uint64     `gorm:"column:block_timestamp;type:bigint unsigned;not null" json:"block_timestamp"`
	TransactionHash  string     `gorm:"column:transaction_hash;type:varchar(66);not null;uniqueIndex:uk_tx_log,priority:1" json:"transaction_hash"`
	LogIndex         int32      `gorm:"column:log_index;type:int;not null;uniqueIndex:uk_tx_log,priority:2" json:"log_index"`
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName EventSetMetanodePerBlock's table name
func (*EventSetMetanodePerBlock) TableName() string {
	return TableNameEventSetMetanodePerBlock
}
