// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePoolInfo = "pool_info"

// PoolInfo 资金池信息表
type PoolInfo struct {
	ID                  int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	PoolID              int32      `gorm:"column:pool_id;type:int;not null;uniqueIndex:uk_pool_contract,priority:1;comment:资金池ID" json:"pool_id"`                                                        // 资金池ID
	ContractAddress     string     `gorm:"column:contract_address;type:varchar(42);not null;uniqueIndex:uk_pool_contract,priority:2;index:idx_contract,priority:1;comment:合约地址" json:"contract_address"` // 合约地址
	StTokenAddress      string     `gorm:"column:st_token_address;type:varchar(42);not null;index:idx_st_token,priority:1;comment:质押代币地址 (0x0 表示ETH)" json:"st_token_address"`                           // 质押代币地址 (0x0 表示ETH)
	PoolWeight          float64    `gorm:"column:pool_weight;type:decimal(30,0);not null;comment:资金池权重" json:"pool_weight"`                                                                              // 资金池权重
	LastRewardBlock     uint64     `gorm:"column:last_reward_block;type:bigint unsigned;not null;comment:最后奖励区块" json:"last_reward_block"`                                                               // 最后奖励区块
	AccMetanodePerSt    *float64   `gorm:"column:acc_metanode_per_st;type:decimal(65,18);default:0.000000000000000000;comment:每质押代币累计MetaNode" json:"acc_metanode_per_st"`                               // 每质押代币累计MetaNode
	StTokenAmount       *float64   `gorm:"column:st_token_amount;type:decimal(65,18);default:0.000000000000000000;comment:质押代币总量" json:"st_token_amount"`                                                // 质押代币总量
	MinDepositAmount    float64    `gorm:"column:min_deposit_amount;type:decimal(65,18);not null;comment:最小质押金额" json:"min_deposit_amount"`                                                              // 最小质押金额
	UnstakeLockedBlocks int32      `gorm:"column:unstake_locked_blocks;type:int;not null;comment:解锁区块数" json:"unstake_locked_blocks"`                                                                    // 解锁区块数
	TotalPoolWeight     *float64   `gorm:"column:total_pool_weight;type:decimal(30,0);comment:所有池的总权重" json:"total_pool_weight"`                                                                         // 所有池的总权重
	IsActive            *bool      `gorm:"column:is_active;type:tinyint(1);default:1;comment:是否激活" json:"is_active"`                                                                                     // 是否激活
	CreatedBlock        *uint64    `gorm:"column:created_block;type:bigint unsigned;comment:创建时的区块号" json:"created_block"`                                                                               // 创建时的区块号
	CreatedTx           *string    `gorm:"column:created_tx;type:varchar(66);comment:创建交易哈希" json:"created_tx"`                                                                                          // 创建交易哈希
	CreatedAt           *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt           *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PoolInfo's table name
func (*PoolInfo) TableName() string {
	return TableNamePoolInfo
}
