// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSyncStatus = "sync_status"

// SyncStatus 区块链同步状态表
type SyncStatus struct {
	ID              int32      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	ContractAddress string     `gorm:"column:contract_address;type:varchar(42);not null;uniqueIndex:uk_contract_chain,priority:1;comment:合约地址" json:"contract_address"` // 合约地址
	ChainID         int32      `gorm:"column:chain_id;type:int;not null;uniqueIndex:uk_contract_chain,priority:2;comment:链ID (如 11155111 for Sepolia)" json:"chain_id"` // 链ID (如 11155111 for Sepolia)
	LastSyncedBlock uint64     `gorm:"column:last_synced_block;type:bigint unsigned;not null;comment:最后同步的区块号" json:"last_synced_block"`                                // 最后同步的区块号
	LastSyncTime    *time.Time `gorm:"column:last_sync_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:最后同步时间" json:"last_sync_time"`                             // 最后同步时间
	SyncError       *string    `gorm:"column:sync_error;type:text;comment:同步错误信息" json:"sync_error"`                                                                    // 同步错误信息
	IsSyncing       *bool      `gorm:"column:is_syncing;type:tinyint(1);comment:是否正在同步" json:"is_syncing"`                                                              // 是否正在同步
	CreatedAt       *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName SyncStatus's table name
func (*SyncStatus) TableName() string {
	return TableNameSyncStatus
}
