// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserPoolStat = "user_pool_stats"

// UserPoolStat 用户资金池统计表
type UserPoolStat struct {
	ID               int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	UserAddress      string     `gorm:"column:user_address;type:varchar(42);not null;uniqueIndex:uk_user_pool,priority:1;index:idx_user,priority:1;comment:用户地址" json:"user_address"` // 用户地址
	PoolID           int32      `gorm:"column:pool_id;type:int;not null;uniqueIndex:uk_user_pool,priority:2;index:idx_pool,priority:1;comment:资金池ID" json:"pool_id"`                  // 资金池ID
	ContractAddress  string     `gorm:"column:contract_address;type:varchar(42);not null;uniqueIndex:uk_user_pool,priority:3;comment:合约地址" json:"contract_address"`                   // 合约地址
	StAmount         *float64   `gorm:"column:st_amount;type:decimal(65,18);index:idx_st_amount,priority:1;default:0.000000000000000000;comment:当前质押金额" json:"st_amount"`             // 当前质押金额
	FinishedMetanode *float64   `gorm:"column:finished_metanode;type:decimal(65,18);default:0.000000000000000000;comment:已领取的MetaNode" json:"finished_metanode"`                      // 已领取的MetaNode
	PendingMetanode  *float64   `gorm:"column:pending_metanode;type:decimal(65,18);default:0.000000000000000000;comment:待领取的MetaNode" json:"pending_metanode"`                        // 待领取的MetaNode
	TotalDeposited   *float64   `gorm:"column:total_deposited;type:decimal(65,18);default:0.000000000000000000;comment:累计质押金额" json:"total_deposited"`                                // 累计质押金额
	TotalUnstaked    *float64   `gorm:"column:total_unstaked;type:decimal(65,18);default:0.000000000000000000;comment:累计解质押金额" json:"total_unstaked"`                                 // 累计解质押金额
	TotalWithdrawn   *float64   `gorm:"column:total_withdrawn;type:decimal(65,18);default:0.000000000000000000;comment:累计提现金额" json:"total_withdrawn"`                                // 累计提现金额
	TotalClaimed     *float64   `gorm:"column:total_claimed;type:decimal(65,18);default:0.000000000000000000;comment:累计领取奖励" json:"total_claimed"`                                    // 累计领取奖励
	LastDepositBlock *uint64    `gorm:"column:last_deposit_block;type:bigint unsigned;comment:最后质押区块" json:"last_deposit_block"`                                                      // 最后质押区块
	LastClaimBlock   *uint64    `gorm:"column:last_claim_block;type:bigint unsigned;comment:最后领取区块" json:"last_claim_block"`                                                          // 最后领取区块
	CreatedAt        *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        *time.Time `gorm:"column:updated_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName UserPoolStat's table name
func (*UserPoolStat) TableName() string {
	return TableNameUserPoolStat
}
